realsense:
  params:
    rs_serial: 941322070969


pipeline:
  params:
    max_num_obj: 2
    estimate_init_pose: true
    frame_to_map_reg: true
    debug_level: 2
    debug_dir: /home/justin/code/point-to-pose/debug/
    save_pose: true
    pose_save_path: /home/justin/code/point-to-pose/debug/poses
    save_key_points: true
    key_points_save_path: /home/justin/code/point-to-pose/debug/key_points
    save_meta_data: true
    meta_data_save_path: /home/justin/code/point-to-pose/debug/pipeline/meta_data
  

register:
  type: svd_uncertainty_outlier
  params:
    remove_outside_mask: false
    debug_level: 0
    max_iter: 5
    threshold_method: mad
    inlier_thres: 0.01
    thres_reduce_factor: 0.005
    mad_scale: 1.0
    min_inliers: 3

segmenter:
  type: sam2
  params:
    model_cfg: configs/sam2.1/sam2.1_hiera_l.yaml
    checkpoint: /home/justin/code/point-to-pose/checkpoints/sam2.1/sam2.1_hiera_large.pt
    device: cuda

tracker:
  type: tapir
  params:
    resize_height: 256
    resize_width: 256
    device: cuda
    checkpoint_path: /home/justin/code/point-to-pose/checkpoints/tapir/causal_bootstapir_checkpoint.pt

sampler: 
  type: uniform_fps
  params:
    num_points: 15
    edge_margin_px: 10
    remove_convex_hull: False
    debug_level: 2
    debug_dir: /home/justin/code/point-to-pose/debug/sampler

criterion:
  ### criterion types: 
  ###      iteration, registration_residual, 
  ###      uncertainty_ratio, uncertainty_number, 
  ###      rotation_grid, rotation_threshold
  ###      mask_area
  type: mask_area
  params:
    # iteration criterion
    update_per_iter: 1000000

    # residual criterion
    residual_thres: 0.02

    # uncertainty criterion
    uncer_thres: 0.3
    min_num_pts: 8

    # rotation grid criterion
    discretization_angle: 60

    # rotation threshold criterion
    max_angle_deg: 40

    # mask area criterion
    fit_mode: convex
    ratio_threshold: 0.4
    debug_viz: false
    debug_dir: /home/justin/code/point-to-pose/debug/criterion

optimizer:
  type: isam2
  params:
    relinearize_threshold: 0.1
    relinearize_skip: 1
    prior_noise_param: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

visualization:
  params:
    visualize_points: true
    points_vis_method: frame_id
    save_images: True
    output_image_dir: /home/justin/code/point-to-pose/debug/output_images