#!/usr/bin/env python3
"""
Interactive point cloud visualization for debug/register folder.
Navigate through point clouds using 'n' for next frame, 'p' for previous frame, 'q' to quit.
Note: Code partially generated by AI
## TODO: N for next frame does not work
"""

import os
import argparse
import glob
from typing import List, Optional

import numpy as np
import open3d as o3d


def find_available_frames(register_folder: str, object_number: int) -> List[int]:
    """Find all available frame numbers for a given object."""
    pattern = os.path.join(register_folder, f"obj_{object_number}_frame_*.ply")
    files = glob.glob(pattern)

    frame_numbers = []
    for file in files:
        filename = os.path.basename(file)
        # Extract frame number from filename like "obj_0_frame_1.ply"
        try:
            frame_part = filename.split("_frame_")[1].split(".")[0]
            frame_numbers.append(int(frame_part))
        except (IndexError, ValueError):
            continue

    return sorted(frame_numbers)


def load_point_cloud(
    register_folder: str, object_number: int, frame_number: int
) -> Optional[o3d.geometry.PointCloud]:
    """Load a point cloud from the register folder."""
    filename = f"obj_{object_number}_frame_{frame_number}.ply"
    filepath = os.path.join(register_folder, filename)

    if not os.path.exists(filepath):
        print(f"Warning: File {filepath} does not exist")
        return None

    try:
        pcd = o3d.io.read_point_cloud(filepath)
        if len(pcd.points) == 0:
            print(f"Warning: Point cloud {filename} is empty")
            return None
        return pcd
    except (IOError, ValueError) as e:
        print(f"Error loading {filename}: {e}")
        return None


def interactive_visualization(
    register_folder: str,
    object_number: int,
    available_frames: List[int],
    start_frame: int,
):
    """Interactive visualization with keyboard navigation."""
    current_frame_idx = available_frames.index(start_frame)

    print("\nNavigation controls:")
    print("  'n' or 'N': Next frame")
    print("  'p' or 'P': Previous frame")
    print("  'q' or 'Q': Quit")

    while True:
        frame_number = available_frames[current_frame_idx]
        print(
            f"\nCurrent frame: {frame_number} (frame {current_frame_idx + 1} of {len(available_frames)})"
        )

        # Load point cloud
        pcd = load_point_cloud(register_folder, object_number, frame_number)
        if pcd is None:
            print(f"Failed to load frame {frame_number}")
            # Move to next frame if current one fails
            if current_frame_idx < len(available_frames) - 1:
                current_frame_idx += 1
                continue
            else:
                print("No more frames available")
                return

        print(
            f"Displaying: obj_{object_number}_frame_{frame_number}.ply ({len(pcd.points)} points)"
        )

        # Create visualization
        vis = o3d.visualization.Visualizer()
        vis.create_window(window_name=f"Object {object_number} - Frame {frame_number}")
        vis.add_geometry(pcd)

        # Set up render options
        render_option = vis.get_render_option()
        render_option.point_size = 10.0
        render_option.show_coordinate_frame = True
        render_option.background_color = [1.0, 1.0, 1.0]  # White background

        # Run visualization (this will block until window is closed)
        vis.run()
        vis.destroy_window()

        # Get user input for next action
        while True:
            try:
                user_input = (
                    input("\nEnter command (n=next, p=previous, q=quit): ")
                    .strip()
                    .lower()
                )
            except (KeyboardInterrupt, EOFError):
                print("\nExiting visualization...")
                return

            if user_input in ["n", "next"]:
                if current_frame_idx < len(available_frames) - 1:
                    current_frame_idx += 1
                    break
                else:
                    print("Already at the last frame!")
                    continue
            elif user_input in ["p", "prev", "previous"]:
                if current_frame_idx > 0:
                    current_frame_idx -= 1
                    break
                else:
                    print("Already at the first frame!")
                    continue
            elif user_input in ["q", "quit"]:
                print("Exiting visualization...")
                return
            else:
                print("Invalid command. Please enter 'n', 'p', or 'q'.")
                continue


def main(args):
    """Main visualization function."""
    # Construct register folder path
    if args.register_folder:
        register_folder = args.register_folder
    else:
        # Use default debug/register folder
        project_root = os.path.dirname(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        )
        register_folder = os.path.join(project_root, "debug", "register")

    if not os.path.exists(register_folder):
        print(f"Error: Register folder {register_folder} does not exist")
        return

    # Find available frames for the specified object
    available_frames = find_available_frames(register_folder, args.object_number)

    if not available_frames:
        print(f"No frames found for object {args.object_number} in {register_folder}")
        print("Available files:")
        all_files = glob.glob(os.path.join(register_folder, "*.ply"))
        for file in all_files:
            print(f"  {os.path.basename(file)}")
        return

    print(
        f"Found {len(available_frames)} frames for object {args.object_number}: {available_frames}"
    )

    # Determine starting frame
    if args.frame_number is not None:
        if args.frame_number not in available_frames:
            print(
                f"Frame {args.frame_number} not found. Available frames: {available_frames}"
            )
            print(f"Using first available frame: {available_frames[0]}")
            start_frame = available_frames[0]
        else:
            start_frame = args.frame_number
    else:
        start_frame = available_frames[0]

    # Load initial point cloud
    print(f"Loading initial frame {start_frame}...")
    pcd = load_point_cloud(register_folder, args.object_number, start_frame)

    if pcd is None:
        print(
            f"Failed to load initial point cloud for object {args.object_number}, frame {start_frame}"
        )
        return

    print(f"Successfully loaded: obj_{args.object_number}_frame_{start_frame}.ply")
    print("Point cloud info:")
    print(f"  - Number of points: {len(pcd.points)}")
    print(f"  - Has colors: {pcd.has_colors()}")
    print(f"  - Has normals: {pcd.has_normals()}")

    # Start interactive visualization
    interactive_visualization(
        register_folder, args.object_number, available_frames, start_frame
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Interactive point cloud visualization for debug/register folder"
    )

    parser.add_argument(
        "--object_number",
        "-o",
        type=int,
        required=True,
        help="Object number to visualize (e.g., 0, 1, 2...)",
    )

    parser.add_argument(
        "--frame_number",
        "-f",
        type=int,
        default=None,
        help="Starting frame number (optional, defaults to first available frame)",
    )

    parser.add_argument(
        "--register_folder",
        "-r",
        type=str,
        default=None,
        help="Path to register folder (optional, defaults to project_root/debug/register)",
    )

    args = parser.parse_args()

    main(args)
