#!/usr/bin/env python3
"""
Interactive point cloud visualization for debug/register folder.
Navigate through point clouds using 'n' for next frame, 'p' for previous frame, 'q' to quit.
Supports correspondence visualization with colored points and connecting lines.
Note: Code partially generated by AI
## TODO: N for next frame does not work
"""

import os
import argparse
import glob
from typing import List, Optional, Tuple

import numpy as np
import open3d as o3d

try:
    import matplotlib
except ImportError:
    matplotlib = None
    print("matplotlib is required for keyframe coloring")


def find_available_frames(register_folder: str, object_number: int) -> List[int]:
    """Find all available frame numbers for a given object."""
    pattern = os.path.join(register_folder, f"obj_{object_number}_frame_*.ply")
    files = glob.glob(pattern)

    frame_numbers = []
    for file in files:
        filename = os.path.basename(file)
        # Extract frame number from filename like "obj_0_frame_1.ply"
        try:
            frame_part = filename.split("_frame_")[1].split(".")[0]
            frame_numbers.append(int(frame_part))
        except (IndexError, ValueError):
            continue

    return sorted(frame_numbers)


def load_point_cloud(
    register_folder: str, object_number: int, frame_number: int, refine: bool = False
) -> Optional[o3d.geometry.PointCloud]:
    """Load a point cloud from the register folder."""
    if refine:
        filename = f"obj_{object_number}_frame_{frame_number}_refine.ply"
    else:
        filename = f"obj_{object_number}_frame_{frame_number}.ply"
    filepath = os.path.join(register_folder, filename)
    print(f"Loading file: {filepath}")
    if not os.path.exists(filepath):
        print(f"Warning: File {filepath} does not exist")
        return None

    try:
        pcd = o3d.io.read_point_cloud(filepath)
        if len(pcd.points) == 0:
            print(f"Warning: Point cloud {filename} is empty")
            return None
        return pcd
    except (IOError, ValueError) as e:
        print(f"Error loading {filename}: {e}")
        return None


def load_correspondence_data(
    register_folder: str, object_number: int, frame_number: int, refine: bool = False
) -> Optional[Tuple[np.ndarray, np.ndarray, np.ndarray]]:
    """Load correspondence data from meata_data.npz file.

    Extracts key_points and curr3d from reg_stats to establish correspondences.
    The key_points (previous frame) and curr3d (current frame) are already in correspondence.

    Args:
        register_folder: Path to register folder
        object_number: Object number (currently only supports object 0)
        frame_number: Frame number to extract correspondences for
        refine: Not used in this implementation (kept for compatibility)

    Returns:
        Tuple of (key_points, curr3d, inliers) if data is found, None otherwise.
        inliers is a boolean array indicating which correspondences are inliers.
    """
    # Look for meata_data.npz in the register folder or parent directories
    meata_data_paths = [
        os.path.join(register_folder, "meata_data.npz"),
        os.path.join(os.path.dirname(register_folder), "meata_data.npz"),
        os.path.join(
            os.path.dirname(os.path.dirname(register_folder)),
            "debug",
            "pipeline",
            "meta_data",
            "meata_data.npz",
        ),
    ]

    meata_data_path = None
    for path in meata_data_paths:
        if os.path.exists(path):
            meata_data_path = path
            break

    if meata_data_path is None:
        print("No meata_data.npz found in expected locations")
        return None

    try:
        # Load the NPZ file
        data = np.load(meata_data_path, allow_pickle=True)
        print(f"Loaded meata_data.npz from: {meata_data_path}")

        # Extract frame_id array to find the correct frame
        if "frame_id" not in data:
            print("No frame_id field found in meata_data.npz")
            return None

        frame_ids = data["frame_id"]
        frame_idx = None

        # Find the index of the requested frame
        for i, fid in enumerate(frame_ids):
            if fid == frame_number:
                frame_idx = i
                break

        if frame_idx is None:
            print(f"Frame {frame_number} not found in meata_data.npz")
            print(f"Available frames: {frame_ids}")
            return None

        # Extract key_points, curr3d, and inliers for the specific frame
        # These are stored as ragged arrays by DataLogger
        key_points = None
        curr3d = None
        inliers = None

        # Extract key_points from reg_key_points (registration key points)
        if (
            "reg_key_points_data" in data
            and "reg_key_points_offsets" in data
            and "reg_key_points_lengths" in data
        ):
            offsets = data["reg_key_points_offsets"]
            lengths = data["reg_key_points_lengths"]
            data_array = data["reg_key_points_data"]

            if frame_idx < len(offsets):
                start_idx = offsets[frame_idx]
                end_idx = start_idx + lengths[frame_idx]
                key_points_flat = data_array[start_idx:end_idx]
                # Reshape to (N, 3) assuming 3D points
                if len(key_points_flat) % 3 == 0:
                    key_points = key_points_flat.reshape(-1, 3)
                else:
                    print(
                        f"Warning: reg_key_points data length {len(key_points_flat)} not divisible by 3"
                    )
                    return None

        # Extract curr3d from reg_curr3d (registration current 3D points)
        if (
            "reg_curr3d_data" in data
            and "reg_curr3d_offsets" in data
            and "reg_curr3d_lengths" in data
        ):
            offsets = data["reg_curr3d_offsets"]
            lengths = data["reg_curr3d_lengths"]
            data_array = data["reg_curr3d_data"]

            if frame_idx < len(offsets):
                start_idx = offsets[frame_idx]
                end_idx = start_idx + lengths[frame_idx]
                curr3d_flat = data_array[start_idx:end_idx]
                # Reshape to (N, 3) assuming 3D points
                if len(curr3d_flat) % 3 == 0:
                    curr3d = curr3d_flat.reshape(-1, 3)
                else:
                    print(
                        f"Warning: reg_curr3d data length {len(curr3d_flat)} not divisible by 3"
                    )
                    return None

        # Extract inliers from reg_inliers
        if (
            "reg_inliers_data" in data
            and "reg_inliers_offsets" in data
            and "reg_inliers_lengths" in data
        ):
            offsets = data["reg_inliers_offsets"]
            lengths = data["reg_inliers_lengths"]
            data_array = data["reg_inliers_data"]

            if frame_idx < len(offsets):
                start_idx = offsets[frame_idx]
                end_idx = start_idx + lengths[frame_idx]
                inliers_flat = data_array[start_idx:end_idx]
                # Convert to boolean array
                inliers = inliers_flat.astype(bool)

        if key_points is None or curr3d is None:
            print(f"Could not extract key_points or curr3d for frame {frame_number}")
            if key_points is None:
                print("key_points extraction failed")
            if curr3d is None:
                print("curr3d extraction failed")
            return None

        # Ensure they have the same number of points
        if len(key_points) != len(curr3d):
            print(
                f"Warning: Mismatch in correspondence count - key_points: {len(key_points)}, curr3d: {len(curr3d)}"
            )
            # Take the minimum length to ensure correspondence
            min_len = min(len(key_points), len(curr3d))
            key_points = key_points[:min_len]
            curr3d = curr3d[:min_len]

        # Load pose data and transform keypoints
        if "obj_pose" in data and "obj_init_pose" in data:
            obj_pose = data["obj_pose"][frame_idx]  # Current pose for this frame
            # obj_init_pose = data["obj_init_pose"][frame_idx]  # Initial pose for this frame -- unused

            # Transform keypoints: key_points_transformed = obj_pose @ (obj_init_pose.inv()) @ key_points
            # First transform to homogeneous coordinates
            key_points_homo = np.hstack([key_points, np.ones((len(key_points), 1))])

            # Apply transformation: obj_pose @ (obj_init_pose.inv())
            transform = obj_pose
            key_points_transformed_homo = (transform @ key_points_homo.T).T

            # Convert back to 3D coordinates
            key_points = key_points_transformed_homo[:, :3]

            print(f"Transformed key_points using pose transformation")
        else:
            print(
                "Warning: obj_pose or obj_init_pose not found, using original key_points"
            )

        # If inliers is None, assume all points are inliers
        if inliers is None:
            inliers = np.ones(len(key_points), dtype=bool)
            print("Warning: reg_inliers not found, assuming all points are inliers")
        else:
            print(
                f"Loaded inliers data: {np.sum(inliers)} inliers out of {len(inliers)} total"
            )

        print(f"Loaded correspondence data: {len(key_points)} correspondences")
        return key_points, curr3d, inliers

    except (IOError, ValueError, KeyError) as e:
        print(f"Error loading correspondence data from {meata_data_path}: {e}")
        return None


def create_correspondence_visualization(
    source_points: np.ndarray, target_points: np.ndarray, inliers: np.ndarray
) -> List[o3d.geometry.Geometry]:
    """Create visualization objects for correspondences.

    Args:
        source_points: Array of source points (N, 3)
        target_points: Array of target points (N, 3)
        inliers: Boolean array indicating which correspondences are inliers (N,)

    Returns:
        List of Open3D geometry objects for visualization
    """
    geometries = []

    # Create point clouds for source and target points
    source_pcd = o3d.geometry.PointCloud()
    source_pcd.points = o3d.utility.Vector3dVector(source_points)

    target_pcd = o3d.geometry.PointCloud()
    target_pcd.points = o3d.utility.Vector3dVector(target_points)

    # Generate unique colors for each correspondence pair
    num_correspondences = len(source_points)
    colors = np.random.rand(
        num_correspondences, 3
    )  # Random colors for each correspondence

    # Set colors for source points - red for outliers, random colors for inliers
    source_colors = colors.copy()
    source_colors[~inliers] = [1.0, 0.0, 0.0]  # Red for outliers
    source_pcd.colors = o3d.utility.Vector3dVector(source_colors)

    # Set colors for target points - red for outliers, same random colors for inliers
    target_colors = colors.copy()
    target_colors[~inliers] = [1.0, 0.0, 0.0]  # Red for outliers
    target_pcd.colors = o3d.utility.Vector3dVector(target_colors)

    geometries.append(source_pcd)
    geometries.append(target_pcd)

    # Create lines connecting corresponding points (only for inliers)
    all_points = np.vstack([source_points, target_points])
    lines = []
    line_colors = []

    for i in range(num_correspondences):
        if inliers[i]:  # Only create lines for inliers
            # Each line connects source point i to target point i
            # Source point is at index i, target point is at index i + num_correspondences
            lines.append([i, i + num_correspondences])
            line_colors.append(colors[i])

    # Create line set only if there are inliers
    if len(lines) > 0:
        line_set = o3d.geometry.LineSet()
        line_set.points = o3d.utility.Vector3dVector(all_points)
        line_set.lines = o3d.utility.Vector2iVector(lines)
        line_set.colors = o3d.utility.Vector3dVector(line_colors)
        geometries.append(line_set)

    return geometries


def color_points_via_nearest_neighbors(
    pcd_points: np.ndarray,
    curr3d: np.ndarray,
    key_frame_ids: np.ndarray,
    inliers: Optional[np.ndarray],
):
    """Return colors array for all pcd_points, coloring only those nearest to curr3d points by key_frame_ids.
    Unmatched remain grey. Outliers are colored red.
    """
    # Default grey
    colors = np.full((len(pcd_points), 3), 0.6, dtype=np.float64)
    if curr3d is None or key_frame_ids is None or len(curr3d) == 0:
        return colors
    # Build KDTree on pcd_points (use PointCloud to avoid API issues)
    pc = o3d.geometry.PointCloud()
    pc.points = o3d.utility.Vector3dVector(pcd_points)
    kdtree = o3d.geometry.KDTreeFlann(pc)
    # Prepare per-frame palette avoiding red
    uniq_ids = np.unique(key_frame_ids)
    frame_to_color = {}
    if matplotlib is not None:
        # Use modern API if available, fallback otherwise
        cmap_get = getattr(getattr(matplotlib, "colormaps", matplotlib.cm), "get_cmap")
        tab10_colors = cmap_get("tab10")
        cmap_indices = {
            fid: i if i < 3 else i + 1 for i, fid in enumerate(sorted(uniq_ids))
        }
        frame_to_color = {
            fid: tab10_colors(idx % 10)[:3] for fid, idx in cmap_indices.items()
        }
    else:
        # Fallback palette excluding red
        palette = [
            (0.2, 0.2, 1.0),
            (0.0, 0.7, 0.3),
            (1.0, 0.6, 0.0),
            (0.6, 0.0, 0.8),
            (0.0, 0.7, 0.7),
            (0.6, 0.6, 0.0),
        ]
        for i, fid in enumerate(sorted(uniq_ids)):
            frame_to_color[fid] = palette[i % len(palette)]
    # Map each curr3d to nearest pcd point index
    used_indices = set()
    for i, pt in enumerate(curr3d):
        # Skip invalid points
        if pt is None or not np.all(np.isfinite(pt)):
            continue
        try:
            k, idxs, _ = kdtree.search_knn_vector_3d(pt, 1)
        except Exception:
            continue
        if k <= 0 or len(idxs) == 0:
            continue
        j = int(idxs[0])
        if j in used_indices or j < 0 or j >= len(pcd_points):
            continue
        used_indices.add(j)
        # Outlier handling: red for outliers only
        if inliers is not None and i < len(inliers) and not bool(inliers[i]):
            colors[j] = [1.0, 0.0, 0.0]
        else:
            c = frame_to_color.get(key_frame_ids[i], (0.5, 0.5, 0.5))
            # Ensure not red for non-outliers
            if c[0] == 1.0 and c[1] == 0.0 and c[2] == 0.0:
                c = (0.2, 0.2, 1.0)
            colors[j] = c
    return colors


def interactive_visualization(
    register_folder: str,
    object_number: int,
    available_frames: List[int],
    start_frame: int,
    refine: bool = False,
    visualize_correspondence: bool = False,
    args=None,
):
    """Interactive visualization with keyboard navigation."""
    current_frame_idx = available_frames.index(start_frame)

    print("\nNavigation controls:")
    print("  'n' or 'N': Next frame")
    print("  'p' or 'P': Previous frame")
    print("  'q' or 'Q': Quit")

    while True:
        frame_number = available_frames[current_frame_idx]
        print(
            f"\nCurrent frame: {frame_number} (frame {current_frame_idx + 1} of {len(available_frames)})"
        )

        # Load point cloud
        pcd = load_point_cloud(register_folder, object_number, frame_number, refine)
        if pcd is None:
            print(f"Failed to load frame {frame_number}")
            # Move to next frame if current one fails
            if current_frame_idx < len(available_frames) - 1:
                current_frame_idx += 1
                continue
            else:
                print("No more frames available")
                return

        print(
            f"Displaying: obj_{object_number}_frame_{frame_number}.ply ({len(pcd.points)} points)"
        )

        vis = o3d.visualization.Visualizer()
        vis.create_window(window_name=f"Object {object_number} - Frame {frame_number}")

        # Debug: Check if show_all_keypoints flag is set
        show_all_kps_flag = (
            getattr(args, "show_all_keypoints", False) if args is not None else False
        )
        print(f"DEBUG: show_all_keypoints flag = {show_all_kps_flag}")
        print(f"DEBUG: visualize_correspondence = {visualize_correspondence}")
        print(f"DEBUG: args = {args}")

        if not visualize_correspondence:
            if getattr(args, "color_by_keyframe_id", False):
                key_frame_ids = get_keyframe_ids_for_register_pointcloud(
                    register_folder, object_number, frame_number, refine
                )
                correspondence_data = load_correspondence_data(
                    register_folder, object_number, frame_number, refine
                )
                inliers = None
                curr3d = None
                if correspondence_data is not None:
                    _, curr3d, inliers = correspondence_data
                # Build colors via NN mapping so we only color matched registered points
                colors = color_points_via_nearest_neighbors(
                    np.asarray(pcd.points), curr3d, key_frame_ids, inliers
                )
                pcd.colors = o3d.utility.Vector3dVector(colors)
            vis.add_geometry(pcd)

            # Optionally show all keypoints even when not visualizing correspondences
            if show_all_kps_flag:
                print(
                    "Attempting to load all keypoints from meta_data (without correspondence mode)..."
                )
                all_kps = load_all_key_points_from_meta(
                    register_folder, object_number, frame_number
                )
                if all_kps is not None and len(all_kps) > 0:
                    print(f"Loaded {len(all_kps)} key points from meta_data")
                    print(f"  Keypoints shape: {all_kps.shape}")
                    # Filter out NaN/Inf values before visualization
                    if np.any(~np.isfinite(all_kps)):
                        valid_mask = np.isfinite(all_kps).all(axis=1)
                        all_kps = all_kps[valid_mask]
                        print(
                            f"  Filtered to {len(all_kps)} valid keypoints (removed NaN/Inf)"
                        )
                    if len(all_kps) > 0:
                        print(
                            f"  Keypoints range: x=[{all_kps[:, 0].min():.3f}, {all_kps[:, 0].max():.3f}], y=[{all_kps[:, 1].min():.3f}, {all_kps[:, 1].max():.3f}], z=[{all_kps[:, 2].min():.3f}, {all_kps[:, 2].max():.3f}]"
                        )
                    kps_pcd = o3d.geometry.PointCloud()
                    kps_pcd.points = o3d.utility.Vector3dVector(all_kps)
                    grey = np.array([[0.6, 0.6, 0.6]] * len(all_kps))
                    kps_pcd.colors = o3d.utility.Vector3dVector(grey)
                    vis.add_geometry(kps_pcd)
                    vis.poll_events()
                    vis.update_renderer()
                    print(f"Added {len(all_kps)} key points from meta_data (grey)")
                else:
                    print(
                        f"Warning: load_all_key_points_from_meta returned None or empty array"
                    )

        # Load and visualize correspondence data if requested
        if visualize_correspondence:
            # Optionally show base point cloud when showing all keypoints for context
            if show_all_kps_flag:
                # Add base point cloud for context
                vis.add_geometry(pcd)
                vis.poll_events()
                vis.update_renderer()
                print(f"Added base point cloud for context ({len(pcd.points)} points)")

            correspondence_data = load_correspondence_data(
                register_folder, object_number, frame_number, refine
            )
            if correspondence_data is not None:
                key_points, curr3d, inliers = correspondence_data

                # Optionally add all key points from meta_data as a single color cloud first
                # This ensures all keypoints are shown, and correspondence points will be on top
                if show_all_kps_flag:
                    print("Attempting to load all keypoints from meta_data...")
                    all_kps = load_all_key_points_from_meta(
                        register_folder, object_number, frame_number
                    )
                    if all_kps is not None and len(all_kps) > 0:
                        print(f"Loaded {len(all_kps)} key points from meta_data")
                        print(f"  Keypoints shape: {all_kps.shape}")
                        # Filter out NaN/Inf values before visualization
                        if np.any(~np.isfinite(all_kps)):
                            valid_mask = np.isfinite(all_kps).all(axis=1)
                            all_kps = all_kps[valid_mask]
                            print(
                                f"  Filtered to {len(all_kps)} valid keypoints (removed NaN/Inf)"
                            )
                        if len(all_kps) > 0:
                            print(
                                f"  Keypoints range: x=[{all_kps[:, 0].min():.3f}, {all_kps[:, 0].max():.3f}], y=[{all_kps[:, 1].min():.3f}, {all_kps[:, 1].max():.3f}], z=[{all_kps[:, 2].min():.3f}, {all_kps[:, 2].max():.3f}]"
                            )
                        kps_pcd = o3d.geometry.PointCloud()
                        kps_pcd.points = o3d.utility.Vector3dVector(all_kps)
                        grey = np.array([[0.6, 0.6, 0.6]] * len(all_kps))
                        kps_pcd.colors = o3d.utility.Vector3dVector(grey)
                        vis.add_geometry(kps_pcd)
                        vis.poll_events()
                        vis.update_renderer()
                        print(f"Added {len(all_kps)} key points from meta_data (grey)")
                        print(f"  Note: All keypoints should be visible as grey points")
                    else:
                        print(
                            f"Warning: load_all_key_points_from_meta returned None or empty array"
                        )
                        if all_kps is None:
                            print("  - Function returned None")
                        elif len(all_kps) == 0:
                            print(f"  - Function returned empty array (length 0)")

                # Create correspondence visualization with lines connecting key_points to curr3d
                print(
                    f"Creating correspondence visualization with {len(key_points)} key_points and {len(curr3d)} curr3d points"
                )
                correspondence_geometries = create_correspondence_visualization(
                    key_points, curr3d, inliers
                )
                print(
                    f"Created {len(correspondence_geometries)} geometry objects for correspondence"
                )
                for i, geom in enumerate(correspondence_geometries):
                    vis.add_geometry(geom)
                    vis.poll_events()
                    vis.update_renderer()
                    if isinstance(geom, o3d.geometry.PointCloud):
                        print(f"  Added PointCloud {i} with {len(geom.points)} points")
                    elif isinstance(geom, o3d.geometry.LineSet):
                        print(f"  Added LineSet {i} with {len(geom.lines)} lines")
                num_inliers = np.sum(inliers)
                num_outliers = len(inliers) - num_inliers
                print(
                    f"Added correspondence visualization with {len(key_points)} correspondences ({num_inliers} inliers, {num_outliers} outliers)"
                )
                # Check if lines were created
                line_set_found = any(
                    isinstance(geom, o3d.geometry.LineSet)
                    for geom in correspondence_geometries
                )
                if line_set_found:
                    line_set = next(
                        geom
                        for geom in correspondence_geometries
                        if isinstance(geom, o3d.geometry.LineSet)
                    )
                    print(
                        f"Created {len(line_set.lines)} lines connecting correspondences"
                    )
                else:
                    print("Warning: No LineSet found in correspondence geometries")
            else:
                print("No correspondence data found for this frame")

        # Set up render options
        render_option = vis.get_render_option()
        render_option.point_size = 10.0
        render_option.show_coordinate_frame = True
        render_option.background_color = [1.0, 1.0, 1.0]  # White background

        # Run visualization (this will block until window is closed)
        vis.run()
        vis.destroy_window()

        # Get user input for next action
        while True:
            try:
                user_input = (
                    input("\nEnter command (n=next, p=previous, q=quit): ")
                    .strip()
                    .lower()
                )
            except (KeyboardInterrupt, EOFError):
                print("\nExiting visualization...")
                return

            if user_input in ["n", "next"]:
                if current_frame_idx < len(available_frames) - 1:
                    current_frame_idx += 1
                    break
                else:
                    print("Already at the last frame!")
                    continue
            elif user_input in ["p", "prev", "previous"]:
                if current_frame_idx > 0:
                    current_frame_idx -= 1
                    break
                else:
                    print("Already at the first frame!")
                    continue
            elif user_input in ["q", "quit"]:
                print("Exiting visualization...")
                return
            else:
                print("Invalid command. Please enter 'n', 'p', or 'q'.")
                continue


def main(args):
    """Main visualization function."""
    # Construct register folder path
    if args.register_folder:
        register_folder = args.register_folder
    else:
        # Use default debug/register folder
        project_root = os.path.dirname(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        )
        register_folder = os.path.join(project_root, "debug", "register")

    if not os.path.exists(register_folder):
        print(f"Error: Register folder {register_folder} does not exist")
        return

    # Find available frames for the specified object
    available_frames = find_available_frames(register_folder, args.object_number)

    if not available_frames:
        print(f"No frames found for object {args.object_number} in {register_folder}")
        print("Available files:")
        all_files = glob.glob(os.path.join(register_folder, "*.ply"))
        for file in all_files:
            print(f"  {os.path.basename(file)}")
        return

    print(
        f"Found {len(available_frames)} frames for object {args.object_number}: {available_frames}"
    )

    # Determine starting frame
    if args.frame_number is not None:
        if args.frame_number not in available_frames:
            print(
                f"Frame {args.frame_number} not found. Available frames: {available_frames}"
            )
            print(f"Using first available frame: {available_frames[0]}")
            start_frame = available_frames[0]
        else:
            start_frame = args.frame_number
    else:
        start_frame = available_frames[0]

    # Load initial point cloud
    print(f"Loading initial frame {start_frame}...")
    pcd = load_point_cloud(
        register_folder, args.object_number, start_frame, args.refine
    )

    if pcd is None:
        print(
            f"Failed to load initial point cloud for object {args.object_number}, frame {start_frame}"
        )
        return
    if args.refine:
        print(
            f"Successfully loaded: obj_{args.object_number}_frame_{start_frame}_refine.ply"
        )
    else:
        print(f"Successfully loaded: obj_{args.object_number}_frame_{start_frame}.ply")
    print("Point cloud info:")
    print(f"  - Number of points: {len(pcd.points)}")
    print(f"  - Has colors: {pcd.has_colors()}")
    print(f"  - Has normals: {pcd.has_normals()}")

    # Start interactive visualization
    interactive_visualization(
        register_folder,
        args.object_number,
        available_frames,
        start_frame,
        args.refine,
        args.visualize_correspondence,
        args,
    )


def get_keyframe_ids_for_register_pointcloud(
    register_folder, object_number, frame_number, refine=False
):
    # object_number and refine are unused, kept for compatibility but suppressed linter
    _ = object_number
    _ = refine
    meta_paths = [
        os.path.join(register_folder, "meata_data.npz"),
        os.path.join(os.path.dirname(register_folder), "meata_data.npz"),
        os.path.join(
            os.path.dirname(os.path.dirname(register_folder)),
            "debug",
            "pipeline",
            "meta_data",
            "meata_data.npz",
        ),
    ]
    meta_path = None
    for path in meta_paths:
        if os.path.exists(path):
            meta_path = path
            break
    if meta_path is None:
        print("No meata_data.npz found for coloring by keyframe id")
        return None
    data = np.load(meta_path, allow_pickle=True)
    if "frame_id" not in data:
        print("No frame_id field in meata_data.npz")
        return None
    frame_ids = data["frame_id"]
    frame_idx = None
    for i, fid in enumerate(frame_ids):
        if fid == frame_number:
            frame_idx = i
            break
    if frame_idx is None:
        print(f"Frame {frame_number} not found in meta_data.npz!")
        return None
    key_points_len = data["reg_key_points_lengths"][frame_idx]
    n_kps = key_points_len // 3
    frame_ids_offset = data["obj_key_point_frames_offsets"][frame_idx]
    key_point_frame_ids = data["obj_key_point_frames_data"][
        frame_ids_offset : frame_ids_offset + n_kps
    ]
    if n_kps != len(key_point_frame_ids):
        print(
            f"Warning: key_points_len ({n_kps}) != key_point_frame_ids ({len(key_point_frame_ids)})"
        )
    return key_point_frame_ids[:n_kps]


def assign_point_colors_by_keyframe_id(points, key_frame_ids, inliers=None):
    if matplotlib is None or key_frame_ids is None or len(points) != len(key_frame_ids):
        default_color = np.array([[0.6, 0.6, 0.6]] * len(points))
        return default_color
    uniq_ids = np.unique(key_frame_ids)
    # Use modern API when available
    cmap_get = getattr(getattr(matplotlib, "colormaps", matplotlib.cm), "get_cmap")
    tab10_colors = cmap_get("tab10")
    cmap_indices = {
        fid: i if i < 3 else i + 1 for i, fid in enumerate(sorted(uniq_ids))
    }
    color_map = {}
    for fid, idx in cmap_indices.items():
        color_map[fid] = tab10_colors(idx % 10)[:3]
    result = np.zeros((len(points), 3))
    for i, f in enumerate(key_frame_ids):
        result[i] = color_map.get(f, (0.5, 0.5, 0.5))
    if inliers is not None:
        result[~inliers] = [1.0, 0.0, 0.0]
    return result


def load_all_key_points_from_meta(
    register_folder: str, object_number: int, frame_number: int
):
    # object_number is currently unused (single-object support); keep for future-proofing
    _ = object_number
    meata_data_paths = [
        os.path.join(register_folder, "meata_data.npz"),
        os.path.join(os.path.dirname(register_folder), "meata_data.npz"),
        os.path.join(
            os.path.dirname(os.path.dirname(register_folder)),
            "debug",
            "pipeline",
            "meta_data",
            "meata_data.npz",
        ),
    ]
    meata_data_path = None
    for path in meata_data_paths:
        if os.path.exists(path):
            meata_data_path = path
            break
    if meata_data_path is None:
        print("No meata_data.npz found for loading all key points")
        print(f"  Searched paths: {meata_data_paths}")
        return None
    print(f"Loading all keypoints from: {meata_data_path}")
    try:
        data = np.load(meata_data_path, allow_pickle=True)
        print(
            f"  Loaded NPZ file, available keys: {list(data.keys())[:10]}..."
        )  # Show first 10 keys
        if "frame_id" not in data:
            print("  Error: No frame_id in meata_data.npz")
            return None
        frame_ids = data["frame_id"]
        print(f"  Found {len(frame_ids)} frames in data")
        frame_idx = None
        for i, fid in enumerate(frame_ids):
            if fid == frame_number:
                frame_idx = i
                break
        if frame_idx is None:
            print(
                f"  Error: Frame {frame_number} not found in meata_data.npz for all key points"
            )
            print(f"  Available frames: {frame_ids[:10]}...")  # Show first 10
            return None
        print(f"  Found frame {frame_number} at index {frame_idx}")

        # Expect ragged storage for obj_key_points
        required_keys = [
            "obj_key_points_data",
            "obj_key_points_offsets",
            "obj_key_points_lengths",
        ]
        missing_keys = [k for k in required_keys if k not in data]
        if missing_keys:
            print(f"  Error: Missing keys in meata_data.npz: {missing_keys}")
            print(
                f"  Available keys containing 'obj_key': {[k for k in data.keys() if 'obj_key' in k]}"
            )
            return None
        offsets = data["obj_key_points_offsets"]
        lengths = data["obj_key_points_lengths"]
        flat = data["obj_key_points_data"]
        print(f"  obj_key_points_data shape: {flat.shape}")
        print(f"  obj_key_points_offsets length: {len(offsets)}")
        print(f"  obj_key_points_lengths length: {len(lengths)}")

        if frame_idx >= len(offsets):
            print(f"  Error: frame_idx ({frame_idx}) >= len(offsets) ({len(offsets)})")
            return None
        start_idx = int(offsets[frame_idx])
        end_idx = start_idx + int(lengths[frame_idx])
        print(
            f"  Extracting keypoints from index {start_idx} to {end_idx} (length: {lengths[frame_idx]})"
        )
        pts_flat = flat[start_idx:end_idx]
        if len(pts_flat) % 3 != 0:
            print(f"  Error: obj_key_points length {len(pts_flat)} not divisible by 3")
            return None
        pts = pts_flat.reshape(-1, 3)
        print(f"  Reshaped to {pts.shape} points")

        # Check for NaN in input points
        if np.any(np.isnan(pts)):
            nan_count = np.sum(np.isnan(pts).any(axis=1))
            print(f"  Warning: Found {nan_count} points with NaN values in raw data")
            # Filter out NaN points
            valid_mask = ~np.isnan(pts).any(axis=1)
            pts = pts[valid_mask]
            print(f"  Filtered to {len(pts)} valid points")

        # Transform to current frame using obj_pose if available
        # obj_key_points are stored in the first frame coordinate system
        # obj_pose transforms from first frame to current frame
        if "obj_pose" in data:
            obj_pose = data["obj_pose"][frame_idx]
            print(f"  Applying obj_pose transformation (shape: {obj_pose.shape})")

            # Check if pose matrix is valid
            if np.any(np.isnan(obj_pose)) or np.any(np.isinf(obj_pose)):
                print(
                    f"  Error: obj_pose contains NaN or Inf values, skipping transformation"
                )
                print(f"  obj_pose:\n{obj_pose}")
            else:
                # Transform to homogeneous coordinates
                pts_h = np.hstack([pts, np.ones((len(pts), 1))])
                # Apply transformation: obj_pose transforms points from frame 0 to current frame
                pts_transformed_homo = (obj_pose @ pts_h.T).T
                # Convert back to 3D coordinates
                pts = pts_transformed_homo[:, :3]

                # Check for NaN after transformation and filter them out
                if np.any(np.isnan(pts)):
                    nan_count = np.sum(np.isnan(pts).any(axis=1))
                    print(
                        f"  Warning: Found {nan_count} points with NaN after transformation"
                    )
                    valid_mask = ~np.isnan(pts).any(axis=1)
                    pts = pts[valid_mask]
                    print(f"  Filtered to {len(pts)} valid points after transformation")
                else:
                    print(f"  Transformed points to current frame successfully")
        else:
            print(f"  Warning: obj_pose not found, using points without transformation")

        print(f"  Returning {len(pts)} keypoints")
        if len(pts) > 0:
            print(
                f"  Final keypoints range: x=[{pts[:, 0].min():.3f}, {pts[:, 0].max():.3f}], y=[{pts[:, 1].min():.3f}, {pts[:, 1].max():.3f}], z=[{pts[:, 2].min():.3f}, {pts[:, 2].max():.3f}]"
            )
        return pts
    except (IOError, ValueError, KeyError) as e:
        print(f"Error loading all key points: {e}")
        import traceback

        traceback.print_exc()
        return None


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Interactive point cloud visualization for debug/register folder"
    )

    parser.add_argument(
        "--object_number",
        "-o",
        type=int,
        required=True,
        help="Object number to visualize (e.g., 0, 1, 2...)",
    )

    parser.add_argument(
        "--frame_number",
        "-f",
        type=int,
        default=None,
        help="Starting frame number (optional, defaults to first available frame)",
    )

    parser.add_argument(
        "--register_folder",
        "-i",
        type=str,
        default=None,
        help="Path to register folder (optional, defaults to project_root/debug/register)",
    )

    parser.add_argument(
        "--refine",
        "-r",
        help="visualize refine results",
        default=False,
        action="store_true",
    )

    parser.add_argument(
        "--visualize_correspondence",
        "-c",
        help="visualize correspondence points with colored lines connecting them",
        default=False,
        action="store_true",
    )

    parser.add_argument(
        "--show_all_keypoints",
        "-akp",
        help="when visualizing correspondences, also plot all object key points from meta_data as grey",
        default=False,
        action="store_true",
    )

    parser.add_argument(
        "--color_by_keyframe_id",
        "-kfid",
        help="color each registered point by its originating key frame id (from meta_data)",
        default=False,
        action="store_true",
    )

    args = parser.parse_args()

    main(args)
