#!/usr/bin/env python3
"""
Interactive point cloud visualization for debug/register folder.
Navigate through point clouds using 'n' for next frame, 'p' for previous frame, 'q' to quit.
Supports correspondence visualization with colored points and connecting lines.
Note: Code partially generated by AI
## TODO: N for next frame does not work
"""

import os
import argparse
import glob
from typing import List, Optional, Tuple

import numpy as np
import open3d as o3d


def find_available_frames(register_folder: str, object_number: int) -> List[int]:
    """Find all available frame numbers for a given object."""
    pattern = os.path.join(register_folder, f"obj_{object_number}_frame_*.ply")
    files = glob.glob(pattern)

    frame_numbers = []
    for file in files:
        filename = os.path.basename(file)
        # Extract frame number from filename like "obj_0_frame_1.ply"
        try:
            frame_part = filename.split("_frame_")[1].split(".")[0]
            frame_numbers.append(int(frame_part))
        except (IndexError, ValueError):
            continue

    return sorted(frame_numbers)


def load_point_cloud(
    register_folder: str, object_number: int, frame_number: int, refine: bool = False
) -> Optional[o3d.geometry.PointCloud]:
    """Load a point cloud from the register folder."""
    if refine:
        filename = f"obj_{object_number}_frame_{frame_number}_refine.ply"
    else:
        filename = f"obj_{object_number}_frame_{frame_number}.ply"
    filepath = os.path.join(register_folder, filename)
    print(f"Loading file: {filepath}")
    if not os.path.exists(filepath):
        print(f"Warning: File {filepath} does not exist")
        return None

    try:
        pcd = o3d.io.read_point_cloud(filepath)
        if len(pcd.points) == 0:
            print(f"Warning: Point cloud {filename} is empty")
            return None
        return pcd
    except (IOError, ValueError) as e:
        print(f"Error loading {filename}: {e}")
        return None


def load_correspondence_data(
    register_folder: str, object_number: int, frame_number: int, refine: bool = False
) -> Optional[Tuple[np.ndarray, np.ndarray, np.ndarray]]:
    """Load correspondence data from meata_data.npz file.

    Extracts key_points and curr3d from reg_stats to establish correspondences.
    The key_points (previous frame) and curr3d (current frame) are already in correspondence.

    Args:
        register_folder: Path to register folder
        object_number: Object number (currently only supports object 0)
        frame_number: Frame number to extract correspondences for
        refine: Not used in this implementation (kept for compatibility)

    Returns:
        Tuple of (key_points, curr3d, inliers) if data is found, None otherwise.
        inliers is a boolean array indicating which correspondences are inliers.
    """
    # Look for meata_data.npz in the register folder or parent directories
    meata_data_paths = [
        os.path.join(register_folder, "meata_data.npz"),
        os.path.join(os.path.dirname(register_folder), "meata_data.npz"),
        os.path.join(
            os.path.dirname(os.path.dirname(register_folder)),
            "debug",
            "pipeline",
            "meta_data",
            "meata_data.npz",
        ),
    ]

    meata_data_path = None
    for path in meata_data_paths:
        if os.path.exists(path):
            meata_data_path = path
            break

    if meata_data_path is None:
        print("No meata_data.npz found in expected locations")
        return None

    try:
        # Load the NPZ file
        data = np.load(meata_data_path, allow_pickle=True)
        print(f"Loaded meata_data.npz from: {meata_data_path}")

        # Extract frame_id array to find the correct frame
        if "frame_id" not in data:
            print("No frame_id field found in meata_data.npz")
            return None

        frame_ids = data["frame_id"]
        frame_idx = None

        # Find the index of the requested frame
        for i, fid in enumerate(frame_ids):
            if fid == frame_number:
                frame_idx = i
                break

        if frame_idx is None:
            print(f"Frame {frame_number} not found in meata_data.npz")
            print(f"Available frames: {frame_ids}")
            return None

        # Extract key_points, curr3d, and inliers for the specific frame
        # These are stored as ragged arrays by DataLogger
        key_points = None
        curr3d = None
        inliers = None

        # Extract key_points from reg_key_points (registration key points)
        if (
            "reg_key_points_data" in data
            and "reg_key_points_offsets" in data
            and "reg_key_points_lengths" in data
        ):
            offsets = data["reg_key_points_offsets"]
            lengths = data["reg_key_points_lengths"]
            data_array = data["reg_key_points_data"]

            if frame_idx < len(offsets):
                start_idx = offsets[frame_idx]
                end_idx = start_idx + lengths[frame_idx]
                key_points_flat = data_array[start_idx:end_idx]
                # Reshape to (N, 3) assuming 3D points
                if len(key_points_flat) % 3 == 0:
                    key_points = key_points_flat.reshape(-1, 3)
                else:
                    print(
                        f"Warning: reg_key_points data length {len(key_points_flat)} not divisible by 3"
                    )
                    return None

        # Extract curr3d from reg_curr3d (registration current 3D points)
        if (
            "reg_curr3d_data" in data
            and "reg_curr3d_offsets" in data
            and "reg_curr3d_lengths" in data
        ):
            offsets = data["reg_curr3d_offsets"]
            lengths = data["reg_curr3d_lengths"]
            data_array = data["reg_curr3d_data"]

            if frame_idx < len(offsets):
                start_idx = offsets[frame_idx]
                end_idx = start_idx + lengths[frame_idx]
                curr3d_flat = data_array[start_idx:end_idx]
                # Reshape to (N, 3) assuming 3D points
                if len(curr3d_flat) % 3 == 0:
                    curr3d = curr3d_flat.reshape(-1, 3)
                else:
                    print(
                        f"Warning: reg_curr3d data length {len(curr3d_flat)} not divisible by 3"
                    )
                    return None

        # Extract inliers from reg_inliers
        if (
            "reg_inliers_data" in data
            and "reg_inliers_offsets" in data
            and "reg_inliers_lengths" in data
        ):
            offsets = data["reg_inliers_offsets"]
            lengths = data["reg_inliers_lengths"]
            data_array = data["reg_inliers_data"]

            if frame_idx < len(offsets):
                start_idx = offsets[frame_idx]
                end_idx = start_idx + lengths[frame_idx]
                inliers_flat = data_array[start_idx:end_idx]
                # Convert to boolean array
                inliers = inliers_flat.astype(bool)

        if key_points is None or curr3d is None:
            print(f"Could not extract key_points or curr3d for frame {frame_number}")
            if key_points is None:
                print("key_points extraction failed")
            if curr3d is None:
                print("curr3d extraction failed")
            return None

        # Ensure they have the same number of points
        if len(key_points) != len(curr3d):
            print(
                f"Warning: Mismatch in correspondence count - key_points: {len(key_points)}, curr3d: {len(curr3d)}"
            )
            # Take the minimum length to ensure correspondence
            min_len = min(len(key_points), len(curr3d))
            key_points = key_points[:min_len]
            curr3d = curr3d[:min_len]

        # Load pose data and transform keypoints
        if "obj_pose" in data and "obj_init_pose" in data:
            obj_pose = data["obj_pose"][frame_idx]  # Current pose for this frame
            obj_init_pose = data["obj_init_pose"][
                frame_idx
            ]  # Initial pose for this frame

            # Transform keypoints: key_points_transformed = obj_pose @ (obj_init_pose.inv()) @ key_points
            # First transform to homogeneous coordinates
            key_points_homo = np.hstack([key_points, np.ones((len(key_points), 1))])

            # Apply transformation: obj_pose @ (obj_init_pose.inv())
            transform = obj_pose @ np.linalg.inv(obj_init_pose)
            key_points_transformed_homo = (transform @ key_points_homo.T).T

            # Convert back to 3D coordinates
            key_points = key_points_transformed_homo[:, :3]

            print(f"Transformed key_points using pose transformation")
        else:
            print(
                "Warning: obj_pose or obj_init_pose not found, using original key_points"
            )

        # If inliers is None, assume all points are inliers
        if inliers is None:
            inliers = np.ones(len(key_points), dtype=bool)
            print("Warning: reg_inliers not found, assuming all points are inliers")
        else:
            print(
                f"Loaded inliers data: {np.sum(inliers)} inliers out of {len(inliers)} total"
            )

        print(f"Loaded correspondence data: {len(key_points)} correspondences")
        return key_points, curr3d, inliers

    except (IOError, ValueError, KeyError) as e:
        print(f"Error loading correspondence data from {meata_data_path}: {e}")
        return None


def create_correspondence_visualization(
    source_points: np.ndarray, target_points: np.ndarray, inliers: np.ndarray
) -> List[o3d.geometry.Geometry]:
    """Create visualization objects for correspondences.

    Args:
        source_points: Array of source points (N, 3)
        target_points: Array of target points (N, 3)
        inliers: Boolean array indicating which correspondences are inliers (N,)

    Returns:
        List of Open3D geometry objects for visualization
    """
    geometries = []

    # Create point clouds for source and target points
    source_pcd = o3d.geometry.PointCloud()
    source_pcd.points = o3d.utility.Vector3dVector(source_points)

    target_pcd = o3d.geometry.PointCloud()
    target_pcd.points = o3d.utility.Vector3dVector(target_points)

    # Generate unique colors for each correspondence pair
    num_correspondences = len(source_points)
    colors = np.random.rand(
        num_correspondences, 3
    )  # Random colors for each correspondence

    # Set colors for source points - red for outliers, random colors for inliers
    source_colors = colors.copy()
    source_colors[~inliers] = [1.0, 0.0, 0.0]  # Red for outliers
    source_pcd.colors = o3d.utility.Vector3dVector(source_colors)

    # Set colors for target points - red for outliers, same random colors for inliers
    target_colors = colors.copy()
    target_colors[~inliers] = [1.0, 0.0, 0.0]  # Red for outliers
    target_pcd.colors = o3d.utility.Vector3dVector(target_colors)

    geometries.append(source_pcd)
    geometries.append(target_pcd)

    # Create lines connecting corresponding points (only for inliers)
    lines = []
    line_colors = []

    for i in range(num_correspondences):
        if inliers[i]:  # Only create lines for inliers
            # Each line connects source point i to target point i
            lines.append([i, i + num_correspondences])  # Source to target
            line_colors.append(colors[i])

    # Create line set only if there are inliers
    if len(lines) > 0:
        line_set = o3d.geometry.LineSet()
        line_set.points = o3d.utility.Vector3dVector(
            np.vstack([source_points, target_points])
        )
        line_set.lines = o3d.utility.Vector2iVector(lines)
        line_set.colors = o3d.utility.Vector3dVector(line_colors)
        geometries.append(line_set)

    return geometries


def interactive_visualization(
    register_folder: str,
    object_number: int,
    available_frames: List[int],
    start_frame: int,
    refine: bool = False,
    visualize_correspondence: bool = False,
):
    """Interactive visualization with keyboard navigation."""
    current_frame_idx = available_frames.index(start_frame)

    print("\nNavigation controls:")
    print("  'n' or 'N': Next frame")
    print("  'p' or 'P': Previous frame")
    print("  'q' or 'Q': Quit")

    while True:
        frame_number = available_frames[current_frame_idx]
        print(
            f"\nCurrent frame: {frame_number} (frame {current_frame_idx + 1} of {len(available_frames)})"
        )

        # Load point cloud
        pcd = load_point_cloud(register_folder, object_number, frame_number, refine)
        if pcd is None:
            print(f"Failed to load frame {frame_number}")
            # Move to next frame if current one fails
            if current_frame_idx < len(available_frames) - 1:
                current_frame_idx += 1
                continue
            else:
                print("No more frames available")
                return

        print(
            f"Displaying: obj_{object_number}_frame_{frame_number}.ply ({len(pcd.points)} points)"
        )

        # Create visualization
        vis = o3d.visualization.Visualizer()
        vis.create_window(window_name=f"Object {object_number} - Frame {frame_number}")

        if not visualize_correspondence:
            vis.add_geometry(pcd)

        # Load and visualize correspondence data if requested
        if visualize_correspondence:
            correspondence_data = load_correspondence_data(
                register_folder, object_number, frame_number, refine
            )
            if correspondence_data is not None:
                key_points, curr3d, inliers = correspondence_data
                correspondence_geometries = create_correspondence_visualization(
                    key_points, curr3d, inliers
                )
                for geom in correspondence_geometries:
                    vis.add_geometry(geom)
                num_inliers = np.sum(inliers)
                num_outliers = len(inliers) - num_inliers
                print(
                    f"Added correspondence visualization with {len(key_points)} correspondences ({num_inliers} inliers, {num_outliers} outliers)"
                )
            else:
                print("No correspondence data found for this frame")

        # Set up render options
        render_option = vis.get_render_option()
        render_option.point_size = 10.0
        render_option.show_coordinate_frame = True
        render_option.background_color = [1.0, 1.0, 1.0]  # White background

        # Run visualization (this will block until window is closed)
        vis.run()
        vis.destroy_window()

        # Get user input for next action
        while True:
            try:
                user_input = (
                    input("\nEnter command (n=next, p=previous, q=quit): ")
                    .strip()
                    .lower()
                )
            except (KeyboardInterrupt, EOFError):
                print("\nExiting visualization...")
                return

            if user_input in ["n", "next"]:
                if current_frame_idx < len(available_frames) - 1:
                    current_frame_idx += 1
                    break
                else:
                    print("Already at the last frame!")
                    continue
            elif user_input in ["p", "prev", "previous"]:
                if current_frame_idx > 0:
                    current_frame_idx -= 1
                    break
                else:
                    print("Already at the first frame!")
                    continue
            elif user_input in ["q", "quit"]:
                print("Exiting visualization...")
                return
            else:
                print("Invalid command. Please enter 'n', 'p', or 'q'.")
                continue


def main(args):
    """Main visualization function."""
    # Construct register folder path
    if args.register_folder:
        register_folder = args.register_folder
    else:
        # Use default debug/register folder
        project_root = os.path.dirname(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        )
        register_folder = os.path.join(project_root, "debug", "register")

    if not os.path.exists(register_folder):
        print(f"Error: Register folder {register_folder} does not exist")
        return

    # Find available frames for the specified object
    available_frames = find_available_frames(register_folder, args.object_number)

    if not available_frames:
        print(f"No frames found for object {args.object_number} in {register_folder}")
        print("Available files:")
        all_files = glob.glob(os.path.join(register_folder, "*.ply"))
        for file in all_files:
            print(f"  {os.path.basename(file)}")
        return

    print(
        f"Found {len(available_frames)} frames for object {args.object_number}: {available_frames}"
    )

    # Determine starting frame
    if args.frame_number is not None:
        if args.frame_number not in available_frames:
            print(
                f"Frame {args.frame_number} not found. Available frames: {available_frames}"
            )
            print(f"Using first available frame: {available_frames[0]}")
            start_frame = available_frames[0]
        else:
            start_frame = args.frame_number
    else:
        start_frame = available_frames[0]

    # Load initial point cloud
    print(f"Loading initial frame {start_frame}...")
    pcd = load_point_cloud(
        register_folder, args.object_number, start_frame, args.refine
    )

    if pcd is None:
        print(
            f"Failed to load initial point cloud for object {args.object_number}, frame {start_frame}"
        )
        return
    if args.refine:
        print(
            f"Successfully loaded: obj_{args.object_number}_frame_{start_frame}_refine.ply"
        )
    else:
        print(f"Successfully loaded: obj_{args.object_number}_frame_{start_frame}.ply")
    print("Point cloud info:")
    print(f"  - Number of points: {len(pcd.points)}")
    print(f"  - Has colors: {pcd.has_colors()}")
    print(f"  - Has normals: {pcd.has_normals()}")

    # Start interactive visualization
    interactive_visualization(
        register_folder,
        args.object_number,
        available_frames,
        start_frame,
        args.refine,
        args.visualize_correspondence,
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Interactive point cloud visualization for debug/register folder"
    )

    parser.add_argument(
        "--object_number",
        "-o",
        type=int,
        required=True,
        help="Object number to visualize (e.g., 0, 1, 2...)",
    )

    parser.add_argument(
        "--frame_number",
        "-f",
        type=int,
        default=None,
        help="Starting frame number (optional, defaults to first available frame)",
    )

    parser.add_argument(
        "--register_folder",
        "-i",
        type=str,
        default=None,
        help="Path to register folder (optional, defaults to project_root/debug/register)",
    )

    parser.add_argument(
        "--refine",
        "-r",
        help="visualize refine results",
        default=False,
        action="store_true",
    )

    parser.add_argument(
        "--visualize_correspondence",
        "-c",
        help="visualize correspondence points with colored lines connecting them",
        default=False,
        action="store_true",
    )

    args = parser.parse_args()

    main(args)
