import numpy as np
import matplotlib.pyplot as plt
import argparse
import os
import sys
from scipy.spatial.transform import Rotation as R
from pathlib import Path

# Add project root to path
sys.path.append(str(Path(__file__).resolve().parents[2]))

from point2pose.io.sources.dataset.datareader import Ho3dReader
from point2pose.utils.transform import inverse_SE3


def _set_plot_style():
    """
    Set a nicer default matplotlib style, but fall back gracefully if unavailable.
    """
    try:
        plt.style.use("seaborn-v0_8")
    except Exception:
        try:
            plt.style.use("seaborn")
        except Exception:
            # Keep matplotlib defaults
            pass


# ---------------------- IO Helpers ---------------------- #
def load_logs(log_path):
    """
    Load the .npz file generated by DataLogger.
    """
    if not os.path.exists(log_path):
        print(f"Error: Log file not found at {log_path}")
        sys.exit(1)

    try:
        data = np.load(log_path, allow_pickle=True)
        return data
    except Exception as e:
        print(f"Error loading log file: {e}")
        sys.exit(1)


def ensure_numeric(arr, name):
    """
    Convert ragged/object pose arrays into a proper (N, 4, 4) float64 array.
    Replace None / invalid entries with identity.
    """
    if arr.dtype != object:
        return arr.astype(np.float64)

    print(f"Warning: {name} is object array, attempting to stack...")
    cleaned = []
    for i, item in enumerate(arr):
        if item is None:
            cleaned.append(np.eye(4))
        elif isinstance(item, np.ndarray) and item.shape == ():
            # 0-d array; unwrap and check
            val = item.item()
            if val is None or not isinstance(val, np.ndarray) or val.shape != (4, 4):
                cleaned.append(np.eye(4))
            else:
                cleaned.append(val.astype(float))
        elif np.shape(item) != (4, 4):
            cleaned.append(np.eye(4))
        else:
            cleaned.append(item.astype(float))

    return np.array(cleaned, dtype=np.float64)


def unpack_ragged(data, name):
    """
    Reconstruct a list of arrays from the packed ragged format (data/offsets/lengths).
    Returns a list of numpy arrays (or None if keys missing).
    Fallback: if 'name' exists directly, return that.
    """
    # 1. Check if exists directly (e.g. object array or fixed shape)
    if name in data:
        return data[name]

    # 2. Check for packed ragged format
    key_data = f"{name}_data"
    key_offsets = f"{name}_offsets"
    key_lengths = f"{name}_lengths"

    if key_data not in data or key_offsets not in data or key_lengths not in data:
        return None

    all_data = data[key_data]
    offsets = data[key_offsets]
    lengths = data[key_lengths]

    reconstructed = []
    for off, length in zip(offsets, lengths):
        # Ensure indices are integers
        off = int(off)
        length = int(length)
        reconstructed.append(all_data[off : off + length])

    return reconstructed


# ---------------------- Pose / Error Helpers ---------------------- #
def se3_to_xyz_quat(poses):
    """
    Convert (N, 4, 4) poses to (N, 7) [x, y, z, qx, qy, qz, qw]
    """
    poses = np.asarray(poses)
    N = poses.shape[0]
    xyz = poses[:, :3, 3]

    quats = []
    for i in range(N):
        r = R.from_matrix(poses[i, :3, :3])
        quats.append(r.as_quat())

    quats = np.array(quats)
    return np.hstack([xyz, quats])


def compute_relative_errors(pred_poses, gt_poses):
    """
    Compute per-frame translation and rotation errors.
    Errors are between pred_poses[i] and gt_poses[i], as:
      rel = inv(gt) @ pred
      t_err = ||rel.t||
      r_err = angle(rel.R) in radians
    Returns:
      t_errs: (N,)
      r_errs: (N,)
    """
    pred_poses = np.asarray(pred_poses)
    gt_poses = np.asarray(gt_poses)

    min_len = min(len(pred_poses), len(gt_poses))
    pred_poses = pred_poses[:min_len]
    gt_poses = gt_poses[:min_len]

    t_errs = np.zeros(min_len)
    r_errs = np.zeros(min_len)

    for i in range(min_len):
        rel = np.linalg.inv(gt_poses[i]) @ pred_poses[i]
        t_errs[i] = np.linalg.norm(rel[:3, 3])

        r_mat = rel[:3, :3]
        r = R.from_matrix(r_mat)
        r_errs[i] = np.linalg.norm(r.as_rotvec())

    return t_errs, r_errs


def summarize_error_stats(name, t_err, r_err):
    """
    Print a compact summary of translation / rotation statistics.
    """
    if t_err is None or r_err is None:
        return

    t_err = np.asarray(t_err)
    r_err_deg = np.degrees(np.asarray(r_err))

    def _safe_stats(x):
        if x.size == 0:
            return dict(mean=np.nan, median=np.nan, rmse=np.nan, p90=np.nan, max=np.nan)
        return dict(
            mean=float(np.mean(x)),
            median=float(np.median(x)),
            rmse=float(np.sqrt(np.mean(x**2))),
            p90=float(np.percentile(x, 90)),
            max=float(np.max(x)),
        )

    t_stats = _safe_stats(t_err)
    r_stats = _safe_stats(r_err_deg)

    print(f"\n[{name}] Translation Error (m):")
    print(
        "  mean={mean:.4f}, median={median:.4f}, rmse={rmse:.4f}, "
        "p90={p90:.4f}, max={max:.4f}".format(**t_stats)
    )

    print(f"[{name}] Rotation Error (deg):")
    print(
        "  mean={mean:.2f}, median={median:.2f}, rmse={rmse:.2f}, "
        "p90={p90:.2f}, max={max:.2f}".format(**r_stats)
    )


# ---------------------- Residual Analysis ---------------------- #
def compute_residual_stats(reg_residuals, reg_inliers):
    """
    Compute per-frame mean residual (of inliers) and inlier count.
    Returns:
      mean_residuals: (N,) array, NaN where no data
      inlier_counts: (N,) array, 0 where no data
    """
    N = len(reg_residuals)
    mean_residuals = np.full(N, np.nan)
    inlier_counts = np.zeros(N, dtype=int)

    for i in range(N):
        res = reg_residuals[i]
        # handle case where reg_inliers might be None or shorter
        inl = None
        if reg_inliers is not None and i < len(reg_inliers):
            inl = reg_inliers[i]

        if (
            res is None
            or (isinstance(res, np.ndarray) and res.size == 0)
            or (isinstance(res, list) and len(res) == 0)
        ):
            continue

        res = np.array(res)

        # Check if inliers is valid
        mask = None
        if inl is not None:
            inl = np.array(inl)
            # Basic check: size match
            if inl.size == res.size:
                mask = inl.astype(bool)

        if mask is not None and np.any(mask):
            valid_res = res[mask]
            count = np.sum(mask)
        else:
            # If mask exists but all false -> count=0
            # If mask is None -> use all
            if mask is not None:
                valid_res = []
                count = 0
            else:
                valid_res = res
                count = len(res)

        if len(valid_res) > 0:
            mean_residuals[i] = np.mean(valid_res)
        inlier_counts[i] = count

    return mean_residuals, inlier_counts


def plot_residual_analysis(
    mean_res,
    inlier_counts,
    fe_t_err=None,
    lo_t_err=None,
    gl_t_err=None,
    fe_r_err=None,
    lo_r_err=None,
    gl_r_err=None,
    kf_indices=None,
    save_prefix=None,
):
    """
    Plot registration residuals with extra context and GT errors (if available).

    Layout:
      - Top:  mean residual over time (+ optional global translation error on 2nd y-axis)
      - Mid:  inlier counts over time
      - 3rd:  scatter of residual vs. global translation / rotation error
      - 4th:  histogram of residuals (and optionally global translation error)
    """
    frames = np.arange(len(mean_res))
    # Use independent x-axes so that time-based plots and value-based plots
    # (residual vs. error, histograms) are all readable.
    fig, axes = plt.subplots(4, 1, figsize=(12, 11))
    ax_res, ax_inl, ax_scatter, ax_hist = axes

    valid_mask = ~np.isnan(mean_res)

    # ----- Summary stats -----
    if np.any(valid_mask):
        vals = mean_res[valid_mask]
        print(
            "[Residual] mean={:.4f}, median={:.4f}, p90={:.4f}, max={:.4f}".format(
                float(np.mean(vals)),
                float(np.median(vals)),
                float(np.percentile(vals, 90)),
                float(np.max(vals)),
            )
        )

    # ----- 1) Residual (and optionally translation error) -----
    ax_res.plot(
        frames[valid_mask],
        mean_res[valid_mask],
        ".-",
        label="Mean Residual",
        color="tab:red",
        linewidth=1.0,
        markersize=3,
    )

    # Overlay global translation and rotation errors on secondary/tertiary y-axes if available
    twin_handles = []
    twin_labels = []
    if gl_t_err is not None:
        n = min(len(gl_t_err), len(frames))
        ax_res_t = ax_res.twinx()
        ax_res_t.plot(
            frames[:n],
            gl_t_err[:n],
            "-",
            label="Global Trans. Err (m)",
            color="tab:blue",
            linewidth=1.0,
            alpha=0.8,
        )
        ax_res_t.set_ylabel("Trans. Error (m)", color="tab:blue")
        ax_res_t.tick_params(axis="y", labelcolor="tab:blue")

        # collect handles for joint legend
        twin_handles, twin_labels = ax_res_t.get_legend_handles_labels()

        # Add rotation error on a third y-axis (offset to the right)
        if gl_r_err is not None:
            n_r = min(len(gl_r_err), len(frames))
            ax_res_r = ax_res.twinx()
            # Offset the right spine to make room for rotation error axis
            ax_res_r.spines["right"].set_position(("outward", 60))
            ax_res_r.plot(
                frames[:n_r],
                np.degrees(gl_r_err[:n_r]),
                "--",
                label="Global Rot. Err (deg)",
                color="tab:orange",
                linewidth=1.0,
                alpha=0.8,
            )
            ax_res_r.set_ylabel("Rot. Error (deg)", color="tab:orange")
            ax_res_r.tick_params(axis="y", labelcolor="tab:orange")

            # Add to legend
            r_handles, r_labels = ax_res_r.get_legend_handles_labels()
            twin_handles.extend(r_handles)
            twin_labels.extend(r_labels)

    # Keyframe markers
    if kf_indices is not None:
        for k in kf_indices:
            if 0 <= k < len(frames):
                ax_res.axvline(x=k, color="k", alpha=0.15, linewidth=0.8)

    ax_res.set_ylabel("Mean Residual")
    title = "Registration Residual vs. Global Error"
    if gl_t_err is not None and gl_r_err is not None:
        title = "Registration Residual vs. Global Translation & Rotation Error"
    ax_res.set_title(title)
    ax_res.grid(True, linestyle="--", alpha=0.6)

    # Build combined legend
    base_h, base_l = ax_res.get_legend_handles_labels()
    all_h = base_h + twin_handles
    all_l = base_l + twin_labels
    if all_h:
        ax_res.legend(all_h, all_l, loc="upper left")

    # ----- 2) Inlier count over time -----
    ax_inl.plot(
        frames,
        inlier_counts,
        ".-",
        label="Inlier Count",
        color="tab:green",
        linewidth=1.0,
        markersize=3,
    )
    if kf_indices is not None:
        for k in kf_indices:
            if 0 <= k < len(frames):
                ax_inl.axvline(x=k, color="k", alpha=0.15, linewidth=0.8)
    ax_inl.set_ylabel("# Inliers")
    ax_inl.set_title("Registration Inlier Count")
    ax_inl.grid(True, linestyle="--", alpha=0.6)
    ax_inl.legend(loc="upper left")

    # ----- 3) Scatter: residual vs error (global) -----
    if gl_t_err is not None:
        n = min(len(gl_t_err), len(mean_res))
        valid = valid_mask[:n]
        x_res = mean_res[:n][valid]

        # Use global translation + rotation for analysis
        y_t = gl_t_err[:n][valid]
        y_r = None
        if gl_r_err is not None:
            y_r = np.degrees(gl_r_err[:n])[valid]

        ax_scatter.scatter(
            x_res,
            y_t,
            s=8,
            alpha=0.6,
            label="Trans. Err (m)",
            color="tab:blue",
        )
        if y_r is not None:
            ax_scatter.scatter(
                x_res,
                y_r,
                s=8,
                alpha=0.6,
                label="Rot. Err (deg)",
                color="tab:orange",
            )

        # Correlation analysis
        if x_res.size > 1:
            try:
                corr_t = np.corrcoef(x_res, y_t)[0, 1]
                print(
                    "[Analysis] Corr(residual, global translation error) = {:.3f}".format(
                        float(corr_t)
                    )
                )
                if y_r is not None:
                    corr_r = np.corrcoef(x_res, y_r)[0, 1]
                    print(
                        "[Analysis] Corr(residual, global rotation error) = {:.3f}".format(
                            float(corr_r)
                        )
                    )
            except Exception as e:
                print(f"[Analysis] Correlation computation failed: {e}")

        ax_scatter.set_xlabel("Mean Residual")
        ax_scatter.set_ylabel("Error")
        ax_scatter.set_title("Residual vs. Global GT Error")
        ax_scatter.grid(True, linestyle="--", alpha=0.6)
        ax_scatter.legend(loc="upper left")
    else:
        ax_scatter.text(
            0.5,
            0.5,
            "No GT errors available\n(skipping residual-vs-error analysis)",
            ha="center",
            va="center",
            transform=ax_scatter.transAxes,
        )
        ax_scatter.grid(True, linestyle="--", alpha=0.6)

    # ----- 4) Histogram of residuals (+ optional global translation error) -----
    valid_vals = mean_res[valid_mask]
    if valid_vals.size > 0:
        ax_hist.hist(
            valid_vals,
            bins=40,
            alpha=0.75,
            color="tab:red",
            label="Mean Residual",
        )
        if gl_t_err is not None:
            n_hist = min(len(gl_t_err), len(valid_vals))
            ax_hist.hist(
                gl_t_err[:n_hist],
                bins=40,
                alpha=0.4,
                color="tab:blue",
                label="Global Trans. Err (m)",
            )
        ax_hist.set_xlabel("Value")
        ax_hist.set_ylabel("Count")
        ax_hist.set_title(
            "Distribution of Residuals"
            + (" & Global Error" if gl_t_err is not None else "")
        )
        ax_hist.grid(True, linestyle="--", alpha=0.6)
        ax_hist.legend(loc="upper right")
    else:
        ax_hist.text(
            0.5,
            0.5,
            "No valid residuals to plot",
            ha="center",
            va="center",
            transform=ax_hist.transAxes,
        )
        ax_hist.grid(True, linestyle="--", alpha=0.6)

    plt.tight_layout()

    if save_prefix:
        out_file = f"{save_prefix}_residuals_and_errors.png"
        plt.savefig(out_file, dpi=180)
        print(f"Saved residual+error plot to {out_file}")

    plt.show()


# ---------------------- Plotting: Full Trajectory ---------------------- #
def plot_full_trajectory(
    frontend, local, global_, gt, keyframe_indices, save_prefix=None
):
    """
    Plot x, y, z trajectories and global errors over time.
    Still useful for sanity checks, but optional.
    """
    N = len(global_)
    frames = np.arange(N)

    fe_xyzq = se3_to_xyz_quat(frontend)
    lo_xyzq = se3_to_xyz_quat(local)
    gl_xyzq = se3_to_xyz_quat(global_)
    gt_xyzq = se3_to_xyz_quat(gt) if gt is not None else None

    fig, axes = plt.subplots(3, 1, figsize=(12, 10), sharex=True)
    labels = ["x", "y", "z"]

    for i in range(3):
        ax = axes[i]
        ax.plot(frames, fe_xyzq[:, i], label="Frontend", alpha=0.6, linestyle="--")
        ax.plot(frames, lo_xyzq[:, i], label="Local", alpha=0.6, linestyle=":")
        ax.plot(frames, gl_xyzq[:, i], label="Global (KF)", linewidth=2)
        if gt_xyzq is not None:
            ax.plot(frames, gt_xyzq[:N, i], label="GT", alpha=0.4)

        for kf_idx in keyframe_indices:
            ax.axvline(x=kf_idx, alpha=0.2, linestyle="-", linewidth=1)

        ax.set_ylabel(f"{labels[i]} (m)")
        ax.grid(True)
        if i == 0:
            ax.legend()
            ax.set_title("Translation Trajectory Comparison")

    axes[-1].set_xlabel("Frame")
    plt.tight_layout()
    if save_prefix:
        out_file = f"{save_prefix}_trajectory.png"
        plt.savefig(out_file)
        print(f"Saved trajectory plot to {out_file}")
    plt.show()

    if gt is None:
        return

    # Errors over all frames
    fe_t_err, fe_r_err = compute_relative_errors(frontend, gt)
    lo_t_err, lo_r_err = compute_relative_errors(local, gt)
    gl_t_err, gl_r_err = compute_relative_errors(global_, gt)

    frames_err = np.arange(len(gl_t_err))

    # Translation error
    plt.figure(figsize=(10, 4))
    plt.plot(frames_err, fe_t_err, label="Frontend Err", alpha=0.5)
    plt.plot(frames_err, lo_t_err, label="Local Err", alpha=0.5)
    plt.plot(frames_err, gl_t_err, label="Global Err", linewidth=2)

    for kf_idx in keyframe_indices:
        if kf_idx < len(frames_err):
            plt.axvline(x=kf_idx, alpha=0.2)

    plt.legend()
    plt.title("Translation Error w.r.t GT (All Frames)")
    plt.ylabel("Error (m)")
    plt.xlabel("Frame")
    plt.grid(True)
    if save_prefix:
        out_file = f"{save_prefix}_error_trans_all.png"
        plt.savefig(out_file)
        print(f"Saved translation error plot to {out_file}")
    plt.show()

    # Rotation error
    plt.figure(figsize=(10, 4))
    plt.plot(frames_err, np.degrees(fe_r_err), label="Frontend Err", alpha=0.5)
    plt.plot(frames_err, np.degrees(lo_r_err), label="Local Err", alpha=0.5)
    plt.plot(frames_err, np.degrees(gl_r_err), label="Global Err", linewidth=2)

    for kf_idx in keyframe_indices:
        if kf_idx < len(frames_err):
            plt.axvline(x=kf_idx, alpha=0.2)

    plt.legend()
    plt.title("Rotation Error w.r.t GT (All Frames)")
    plt.ylabel("Error (deg)")
    plt.xlabel("Frame")
    plt.grid(True)
    if save_prefix:
        out_file = f"{save_prefix}_error_rot_all.png"
        plt.savefig(out_file)
        print(f"Saved rotation error plot to {out_file}")
    plt.show()


# ---------------------- Plotting: Keyframe-Only ---------------------- #
def plot_keyframe_errors(
    fe_t_err,
    fe_r_err,
    lo_t_err,
    lo_r_err,
    gl_t_err,
    gl_r_err,
    kf_indices,
    save_prefix=None,
):
    """
    Visualize errors ONLY at keyframes, with translation and rotation
    in a single figure (two stacked bar plots sharing x).

    For each keyframe index k:
      - show three bars: Frontend, Local, Global (KF)
    """
    if len(kf_indices) == 0:
        print("No keyframes found, skipping keyframe error plots.")
        return

    # keep only keyframes that lie within the error arrays
    max_len = min(
        len(fe_t_err),
        len(lo_t_err),
        len(gl_t_err),
        len(fe_r_err),
        len(lo_r_err),
        len(gl_r_err),
    )
    kf_indices = [k for k in kf_indices if k < max_len]

    if len(kf_indices) == 0:
        print("Keyframe indices are all out of bounds for error arrays.")
        return

    # gather per-keyframe errors
    fe_t_kf = fe_t_err[kf_indices]
    lo_t_kf = lo_t_err[kf_indices]
    gl_t_kf = gl_t_err[kf_indices]

    fe_r_kf = np.degrees(fe_r_err[kf_indices])
    lo_r_kf = np.degrees(lo_r_err[kf_indices])
    gl_r_kf = np.degrees(gl_r_err[kf_indices])

    x = np.arange(len(kf_indices))
    width = 0.25

    fig, axes = plt.subplots(2, 1, figsize=(14, 6), sharex=True)
    ax_t, ax_r = axes

    # --- Translation (top) ---
    ax_t.bar(x - width, fe_t_kf, width, label="Frontend")
    ax_t.bar(x, lo_t_kf, width, label="Local")
    ax_t.bar(x + width, gl_t_kf, width, label="Global (KF)")
    ax_t.set_ylabel("Translation Error (m)")
    ax_t.set_title("Pose Error at Keyframes (FE → Local → KF)")
    ax_t.grid(axis="y", linestyle="--", alpha=0.4)
    ax_t.legend(loc="upper left")

    # --- Rotation (bottom) ---
    ax_r.bar(x - width, fe_r_kf, width, label="Frontend")
    ax_r.bar(x, lo_r_kf, width, label="Local")
    ax_r.bar(x + width, gl_r_kf, width, label="Global (KF)")
    ax_r.set_ylabel("Rotation Error (deg)")
    ax_r.set_xlabel("Frame index (Keyframes)")
    ax_r.grid(axis="y", linestyle="--", alpha=0.4)

    # x-ticks = actual KF indices
    ax_r.set_xticks(x)
    ax_r.set_xticklabels(kf_indices, rotation=45)

    plt.tight_layout()
    if save_prefix:
        out_file = f"{save_prefix}_kf_error_trans_rot.png"
        plt.savefig(out_file, dpi=200)
        print(f"Saved keyframe translation+rotation error plot to {out_file}")
    plt.show()


def analyze_keyframe_improvement(
    fe_t_err, lo_t_err, gl_t_err, fe_r_err, lo_r_err, gl_r_err, kf_indices
):
    """
    Print simple statistics showing how errors change FE -> Local -> Global on keyframes.
    """
    if (
        fe_t_err is None
        or lo_t_err is None
        or gl_t_err is None
        or fe_r_err is None
        or lo_r_err is None
        or gl_r_err is None
        or len(kf_indices) == 0
    ):
        return

    kf_indices = np.asarray(kf_indices, dtype=int)
    max_len = min(
        len(fe_t_err),
        len(lo_t_err),
        len(gl_t_err),
        len(fe_r_err),
        len(lo_r_err),
        len(gl_r_err),
    )
    kf_indices = kf_indices[kf_indices < max_len]
    if kf_indices.size == 0:
        return

    fe_t = fe_t_err[kf_indices]
    lo_t = lo_t_err[kf_indices]
    gl_t = gl_t_err[kf_indices]
    fe_r = fe_r_err[kf_indices]
    lo_r = lo_r_err[kf_indices]
    gl_r = gl_r_err[kf_indices]

    def _improvement_rate(before, after):
        better = np.sum(after < before)
        worse = np.sum(after > before)
        same = np.sum(after == before)
        total = float(before.size)
        return dict(
            better=int(better),
            worse=int(worse),
            same=int(same),
            better_pct=100.0 * better / total if total > 0 else np.nan,
            worse_pct=100.0 * worse / total if total > 0 else np.nan,
        )

    print("\n=== Keyframe Improvement Analysis ===")
    t_fe_to_lo = _improvement_rate(fe_t, lo_t)
    t_lo_to_gl = _improvement_rate(lo_t, gl_t)
    r_fe_to_lo = _improvement_rate(fe_r, lo_r)
    r_lo_to_gl = _improvement_rate(lo_r, gl_r)

    print("Translation FE → Local:")
    print(
        "  better={better} ({better_pct:.1f}%), "
        "worse={worse} ({worse_pct:.1f}%), same={same}".format(**t_fe_to_lo)
    )
    print("Translation Local → Global:")
    print(
        "  better={better} ({better_pct:.1f}%), "
        "worse={worse} ({worse_pct:.1f}%), same={same}".format(**t_lo_to_gl)
    )
    print("Rotation FE → Local:")
    print(
        "  better={better} ({better_pct:.1f}%), "
        "worse={worse} ({worse_pct:.1f}%), same={same}".format(**r_fe_to_lo)
    )
    print("Rotation Local → Global:")
    print(
        "  better={better} ({better_pct:.1f}%), "
        "worse={worse} ({worse_pct:.1f}%), same={same}".format(**r_lo_to_gl)
    )


def filter_keyframes_with_gt(kf_indices, gt_poses):
    """
    Return only the subset of keyframe indices that have valid GT.
    GT entries that are identity (0) or None are treated as missing.
    """
    valid_kf = []
    for k in kf_indices:
        if k < 0 or k >= len(gt_poses):
            continue
        G = gt_poses[k]

        # GT may be None, identity, or zeros -> treat as missing
        if G is None:
            continue
        if not isinstance(G, np.ndarray) or G.shape != (4, 4):
            continue
        if np.allclose(G, np.eye(4)):
            # identity might be valid GT OR might mean missing
            # but you said missing GT comes as identity → skip it
            continue

        valid_kf.append(k)

    return np.array(valid_kf, dtype=int)


# ---------------------- Main ---------------------- #
def main():
    parser = argparse.ArgumentParser(
        description="Visualize pose debug for pipeline.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--log_path", type=str, required=True, help="Path to meta_data.npz"
    )
    parser.add_argument("--data_path", type=str, help="Path to HO3D root")
    parser.add_argument("--video_name", type=str, help="Video name for GT loading")
    parser.add_argument(
        "--align_gt", action="store_true", help="Align GT to first frame prediction"
    )
    parser.add_argument(
        "--save_prefix", type=str, help="Prefix for saving output plots (optional)"
    )
    parser.add_argument(
        "--plot_full_trajectory",
        action="store_true",
        help="Also plot full trajectory & per-frame error curves",
    )

    args = parser.parse_args()

    _set_plot_style()

    # 1. Load Logs
    print(f"Loading logs from {args.log_path}...")
    data = load_logs(args.log_path)

    # Extract poses
    if "pose_frontend" not in data:
        print(
            "Error: 'pose_frontend' not found in logs. "
            "Make sure you updated ModularPipeline._log_step to log it."
        )
        sys.exit(1)

    pose_frontend = ensure_numeric(data["pose_frontend"], "pose_frontend")
    pose_local = ensure_numeric(data["pose_local"], "pose_local")
    pose_global = ensure_numeric(data["obj_pose"], "obj_pose")

    print(f"pose_frontend shape: {pose_frontend.shape}, dtype: {pose_frontend.dtype}")
    print(f"pose_local shape: {pose_local.shape}, dtype: {pose_local.dtype}")
    print(f"pose_global shape: {pose_global.shape}, dtype: {pose_global.dtype}")

    # Keyframes
    if "is_key_frame" in data:
        is_key_frame = data["is_key_frame"]
    elif "is_key_frame_data" in data:
        is_key_frame = data["is_key_frame_data"]
    else:
        print("Warning: is_key_frame info not found, assuming no keyframes.")
        is_key_frame = np.zeros(len(pose_global), dtype=bool)

    kf_indices = np.where(is_key_frame)[0]
    print(f"Found {len(kf_indices)} keyframes at indices: {kf_indices}")

    for k in kf_indices:
        T_lo = pose_local[k]
        T_gl = pose_global[k]
        rel = np.linalg.inv(T_lo) @ T_gl

        t = np.linalg.norm(rel[:3, 3])
        r = R.from_matrix(rel[:3, :3])
        ang = np.linalg.norm(r.as_rotvec())
        print(f"KF {k}: Local→Global Δt={t:.4f} m, ΔR={np.degrees(ang):.2f} deg")

    # 2. Load GT if provided
    gt_poses = None
    if args.data_path and args.video_name:
        if not os.path.exists(args.data_path):
            print(
                f"Warning: Data path {args.data_path} does not exist. Skipping GT load."
            )
        else:
            print(f"Loading GT for {args.video_name} from {args.data_path}...")
            # typical HO3D layout: root/evaluation/VIDEO_NAME or root/VIDEO_NAME
            video_path = os.path.join(args.data_path, "evaluation", args.video_name)
            if not os.path.exists(video_path):
                video_path = os.path.join(args.data_path, args.video_name)

            if not os.path.exists(video_path):
                print(
                    f"Warning: Video path {video_path} does not exist. Skipping GT load."
                )
            else:
                try:
                    reader = Ho3dReader(video_path, args.data_path)
                    if len(reader) == 0:
                        print("Warning: Ho3dReader found no frames. Skipping GT load.")
                    else:
                        frame_ids = data["frame_id"]
                        gt_list = []
                        gt_valid = []

                        for fid in frame_ids:
                            idx = int(fid)
                            if idx < 0 or idx >= len(reader):
                                # no GT available
                                gt_list.append(np.eye(4))
                                gt_valid.append(False)
                            else:
                                pose = reader.get_gt_pose(idx)
                                if pose is None:
                                    # no GT available for this frame
                                    gt_list.append(np.eye(4))
                                    gt_valid.append(False)
                                else:
                                    gt_list.append(pose)
                                    gt_valid.append(True)

                        gt_poses = np.array(gt_list)
                        gt_valid = np.array(gt_valid, dtype=bool)

                        if args.align_gt and gt_valid.any():
                            # Align using the FIRST frame that actually has GT
                            first_valid = int(np.where(gt_valid)[0][0])
                            T_align = pose_global[first_valid] @ inverse_SE3(
                                gt_poses[first_valid]
                            )

                            aligned_list = []
                            for G, v in zip(gt_poses, gt_valid):
                                if v:
                                    aligned_list.append(G @ T_align)
                                else:
                                    # keep as identity placeholder, still marked invalid
                                    aligned_list.append(G)
                            gt_poses = np.array(aligned_list)

                            print(
                                f"Aligned GT to first valid frame (idx={first_valid})."
                            )
                except Exception as e:
                    print(f"Failed to load GT: {e}")
                    import traceback

                    traceback.print_exc()
                    gt_poses = None

    if gt_poses is None:
        print("No GT poses loaded; will only visualize trajectories (no errors).")

    # 3. Compute errors (if GT exists)
    fe_t_err = lo_t_err = gl_t_err = fe_r_err = lo_r_err = gl_r_err = None
    if gt_poses is not None:
        fe_t_err, fe_r_err = compute_relative_errors(pose_frontend, gt_poses)
        lo_t_err, lo_r_err = compute_relative_errors(pose_local, gt_poses)
        gl_t_err, gl_r_err = compute_relative_errors(pose_global, gt_poses)

        print("\n========== Global Error Summary ==========")
        summarize_error_stats("Frontend", fe_t_err, fe_r_err)
        summarize_error_stats("Local", lo_t_err, lo_r_err)
        summarize_error_stats("Global (KF)", gl_t_err, gl_r_err)

    # 4. Residual Analysis (always try; overlays errors if present)
    print("Extracting registration residuals...")
    reg_residuals = unpack_ragged(data, "reg_residuals")

    if reg_residuals is not None:
        reg_inliers = unpack_ragged(data, "reg_inliers")
        mean_res, inlier_counts = compute_residual_stats(reg_residuals, reg_inliers)
        plot_residual_analysis(
            mean_res,
            inlier_counts,
            fe_t_err=fe_t_err,
            lo_t_err=lo_t_err,
            gl_t_err=gl_t_err,
            fe_r_err=fe_r_err,
            lo_r_err=lo_r_err,
            gl_r_err=gl_r_err,
            kf_indices=kf_indices,
            save_prefix=args.save_prefix,
        )
    else:
        print(
            "Warning: 'reg_residuals' not found in logs (checked ragged & direct), skipping residual plot."
        )

    # 5. Additional GT-based plots
    if gt_poses is not None:
        # 5a. Keyframe-only error plots
        print("Filtering KF indices that have valid GT...")
        kf_indices_valid = filter_keyframes_with_gt(kf_indices, gt_poses)
        print(f"Valid keyframes with GT: {kf_indices_valid}")

        # Improvement statistics on valid KFs
        analyze_keyframe_improvement(
            fe_t_err,
            lo_t_err,
            gl_t_err,
            fe_r_err,
            lo_r_err,
            gl_r_err,
            kf_indices_valid,
        )

        plot_keyframe_errors(
            fe_t_err,
            fe_r_err,
            lo_t_err,
            lo_r_err,
            gl_t_err,
            gl_r_err,
            kf_indices_valid,
            save_prefix=args.save_prefix,
        )

        # 5b. Optional global / per-frame plots
        if args.plot_full_trajectory:
            plot_full_trajectory(
                pose_frontend,
                pose_local,
                pose_global,
                gt_poses,
                kf_indices,
                save_prefix=args.save_prefix,
            )
    else:
        # No GT; you can still inspect raw poses and keyframe distribution
        if args.plot_full_trajectory:
            plot_full_trajectory(
                pose_frontend,
                pose_local,
                pose_global,
                None,
                kf_indices,
                args.save_prefix,
            )


if __name__ == "__main__":
    main()
