

pipeline:
  type: modular
  params:
    max_num_obj: 1
    estimate_init_pose: false

    use_segmenter: true

    # depth related
    fill_missing_depth: true
    fill_missing_depth_window_size: 5
    fill_missing_depth_min_neighbors: 1
    min_depth: 0.1
    max_depth: 1.5

    use_depth_estimate: false
    depth_estimator_type: depth_anything
    device: cuda
    depth_encoder: vitl

    max_rel_rotation_deg: 15
    max_rel_translation: 0.03

    kf_gating: true
    anchor_rot_deg: 15.0
    anchor_trans: 0.05
    anchor_min_inliers: 10
    anchor_min_inlier_ratio: 0.001
    anchor_max_median_res: 1.0
    anchor_vel_hist_len: 5
    anchor_vel_rot_deg: 300.0
    anchor_vel_trans: 100.0

    sdf_kf_gate : false
    sdf_kf_gate_thres: 0.05
    sdf_kf_gate_percentile: 70.0
    sdf_kf_gate_min_dense: 200

    frame_reg_mode: f2m
    use_dense_registration: false
    use_local_graph: true

    debug_level: 0
    debug_dir: /home/justin/code/point-to-pose/debug/
    save_pose: true
    pose_save_path: /home/justin/code/point-to-pose/debug/poses
    save_key_points: false
    key_points_save_path: /home/justin/code/point-to-pose/debug/key_points
    save_meta_data: true
    meta_data_save_path: /home/justin/code/point-to-pose/debug/pipeline/meta_data
    save_cropped_pcd: false
    cropped_pcd_dir: /home/justin/code/point-to-pose/debug/cropped_pcd

reconstructor:
  type: sdf_builder
  params:
    build_sdf_after_global_opt: true
    sdf_use_gpu: true
    # nvblox, tsdf_python
    sdf_backend: nvblox
    sdf_voxel_size: 0.005
    sdf_bounds_padding: 0.02
    sdf_min_points: 300
    sdf_filter_max_radius: 0.25
    sdf_filter_keep_percentile: 98.0
    sdf_fuse_color: true



# register:
  # svd_ransac, svd_residual_outlier, svd_uncertainty_outlier, svd_cluster_ransac
  # type: svd_residual_outlier
  # params:
  #   remove_outside_mask: true
  #   debug_level: 0
  #   max_iter: 15
  #   uncer_thres: 0.3
  #   threshold_method: mad
  #   inlier_thres: 0.01
  #   thres_reduce_factor: 0.005
  #   mad_scale: 5
  #   min_inliers: 3
  #   min_variance: 1e-2

  #   # outlier pose
  #   residual_thres: 0.007
    
register:
  type: svd_cluster_ransac
  params:
    ransac_iters: 100
    sample_size: 4
    inlier_thres: 0.005
    min_inliers: 5
    max_clusters: 10
    use_uncertainty: true
    min_variance: 1e-2

    # reproj_error, dist_to_prev, inlier_count, mean_residual, reproj_error_iou, 3d_dist, 3d_dist_prev_kf, 3d_dist_sparse_map, 3d_dist_dense_map
    select_method: 3d_dist_dense_map
    select_3d_dist_min_depth: 0.08
    select_3d_dist_max_depth: 1.5
    select_3d_dist_fill_missing_depth: true
    select_3d_dist_window_size: 5
    select_3d_dist_min_neighbors: 1
    select_dense_map_close_margin: 1e-3

    # front end
    remove_outside_mask: true
    uncer_thres: 0.3
    residual_thres: 0.007

# register:
#   type: svd_cluster
#   params:
#     threshold_method: fixed
#     ransac_iters: 50
#     sample_size: 4
#     inlier_thres: 0.005
#     min_inliers: 4
#     max_clusters: 10
#     use_uncertainty: true
#     min_variance: 1e-3

#     select_method: 3d_dist

#     # front end
#     remove_outside_mask: true
#     uncer_thres: 0.3
#     residual_thres: 0.007

# register:
#   type: svd_ransac
#   params:
#     sample_size: 5     
#     max_trials: 300
#     inlier_thres: 0.01
#     min_inliers: 5
#     refine_iters: 1
#     min_triangle_area: 1e-6
#     min_pca_ratio: 1e-3
#     # outlier pose
#     residual_thres: 0.001

dense_register:
  type: cupoch_icp
  params:
    icp_type: point_to_plane
    min_num_points: 5
    max_num_points: 10000
    max_correspondence_distance: 0.05
    max_iterations: 30
    epsilon: 1e-6
    debug_level: 0
    debug_dir: /home/justin/code/point-to-pose/debug/dense_register

segmenter:
  type: sam2
  params:
    model_cfg: configs/sam2.1/sam2.1_hiera_l.yaml
    checkpoint: /home/justin/code/point-to-pose/checkpoints/sam2.1/sam2.1_hiera_large.pt
    device: cuda

tracker:
  type: tapir
  params:
    resize_height: 480
    resize_width: 480
    visible_threshold: 0.5
    device: cuda
    checkpoint_path: /home/justin/code/point-to-pose/checkpoints/tapir/causal_bootstapir_checkpoint.pt
 
  
# tracker:
#   type: cotracker3_online
#   params:
#     img_height: 480
#     img_width: 640
#     resize_height: 480
#     resize_width: 640
#     device: cuda
#     window_len: 16
#     v2: False  
#     checkpoint_path: /home/justin/code/co-tracker-realtime/checkpoints/scaled_online.pth
#     debug: false

sampler: 
  type: uniform_fps
  params:
    num_points: 25
    density_per_kpx: -1
    fps_oversample_factor: 3

    min_points: 5
    max_points: 50
    edge_margin_px: 5
    remove_convex_hull: false
    inflate_points: false
    inflate_radius_px: 20

    cell_size: -1

    crop_to_mask: true
    crop_pad_px: 3

    super_point_max_num_keypoints: 512

    debug_level: 0
    debug_dir: /home/justin/code/point-to-pose/debug/sampler
    debug_save_superpoint: false

criterion:
  ### criterion types: 
  ###      iteration, registration_residual, 
  ###      uncertainty_ratio, uncertainty_number, 
  ###      rotation_grid, rotation_threshold
  ###      mask_area
  type: rotation_threshold_and_min_num
  params:
    # iteration criterion
    update_per_iter: 1000000

    # residual criterion
    residual_thres: 0.02

    # uncertainty criterion
    uncer_thres: 0.3
    min_num_pts: 20

    # rotation threshold and min num criterion
    # if it's smaller than this it will not trigger sampling
    min_mask_area: 100  

    # rotation grid criterion
    discretization_angle: 60

    # rotation threshold criterion
    max_angle_deg: 10

    # mask area criterion
    fit_mode: convex
    ratio_threshold: 0.6
    debug_viz: false
    debug_dir: /home/justin/code/point-to-pose/debug/criterion

local_optimizer:
  type: lm_graph
  params:
    local_graph_max_num_frames: 120
    max_iterations: 20
    relative_error_tol: 1e-5
    absolute_error_tol: 1e-5
    prior_noise_param: [1e-6, 1e-6, 1e-6, 1e-6, 1e-6, 1e-6]
    uncertainty_thres: 0.3
    uncertainty_min: 1e-2
    use_between_factor: true
    landmark_sigma_scale_by: residual
    landmark_sigma_min: 1e-3
    landmark_huber_k: 1.0

global_optimizer:
  type: lm_graph
  params:
    relinearize_threshold: 0.1
    relinearize_skip: 1
    relative_error_tol: 1e-5
    absolute_error_tol: 1e-5
    prior_noise_param: [1e-6, 1e-6, 1e-6, 1e-6, 1e-6, 1e-6]
    uncertainty_thres: 0.3
    uncertainty_min: 1e-2
    use_between_factor: true
    landmark_sigma_scale_by: residual
    landmark_sigma_min: 1e-3
    landmark_huber_k: 1.0

visualization:
  params:
    visualize_points: true
    # uncertainty, visible, visible_uncertainty, frame_id
    points_vis_method: visible_uncertainty
    save_images: True
    output_image_dir: /home/justin/code/point-to-pose/debug/output_images