

pipeline:
  type: modular
  params:
    # sequence_name: auto, MPM10, AP10, etc.
    # dataset_name: ho3d
    # sequence_name: auto
    max_num_obj: 1
    estimate_init_pose: true

    use_segmenter: false

    # depth related
    fill_missing_depth: true
    fill_missing_depth_window_size: 3
    fill_missing_depth_min_neighbors: 1
    min_depth: 0.05
    max_depth: 0.8

    use_depth_estimate: false
    depth_estimator_type: depth_anything
    device: cuda
    depth_encoder: vitl

    use_local_graph: true

    debug_level: 2
    debug_dir: /home/justin/code/point-to-pose/debug/
    save_pose: true
    pose_save_path: /home/justin/code/point-to-pose/debug/poses
    save_key_points: true
    key_points_save_path: /home/justin/code/point-to-pose/debug/key_points
    save_meta_data: true
    meta_data_save_path: /home/justin/code/point-to-pose/debug/pipeline/meta_data
    save_cropped_pcd: true
    cropped_pcd_dir: /home/justin/code/point-to-pose/debug/cropped_pcd

register:
  type: svd_residual_outlier
  params:
    remove_outside_mask: true
    debug_level: 0
    max_iter: 15
    uncer_thres: 0.3
    threshold_method: mad
    inlier_thres: 0.01
    thres_reduce_factor: 0.005
    mad_scale: 5
    min_inliers: 3

    # outlier pose
    residual_thres: 0.07

segmenter:
  type: sam2
  params:
    model_cfg: configs/sam2.1/sam2.1_hiera_l.yaml
    checkpoint: /home/justin/code/point-to-pose/checkpoints/sam2.1/sam2.1_hiera_large.pt
    device: cuda

tracker:
  type: tapir
  params:
    resize_height: 480
    resize_width: 480
    visible_threshold: 0.5
    device: cuda
    checkpoint_path: /home/justin/code/point-to-pose/checkpoints/tapir/causal_bootstapir_checkpoint.pt
 
  
  # type: cotracker3_online
  # params:
  #   img_height: 480
  #   img_width: 640
  #   resize_height: 480
  #   resize_width: 640
  #   device: cuda
  #   window_len: 16
  #   v2: False  # keep False unless you specifically use v2 weights
  #   checkpoint_path: /home/justin/code/co-tracker-realtime/checkpoints/scaled_online.pth
  #   debug: true

sampler: 
  type: super_point
  params:
    num_points: 20
    density_per_kpx: -1

    min_points: 5
    max_points: 50
    edge_margin_px: 3
    remove_convex_hull: false
    inflate_points: false
    inflate_radius_px: 20

    cell_size: -1

    crop_to_mask: true
    crop_pad_px: 3

    super_point_max_num_keypoints: 512

    debug_level: 2
    debug_dir: /home/justin/code/point-to-pose/debug/sampler
    debug_save_superpoint: false

criterion:
  ### criterion types: 
  ###      iteration, registration_residual, 
  ###      uncertainty_ratio, uncertainty_number, 
  ###      rotation_grid, rotation_threshold
  ###      mask_area
  type: rotation_threshold
  params:
    # iteration criterion
    update_per_iter: 1000000

    # residual criterion
    residual_thres: 0.02

    # uncertainty criterion
    uncer_thres: 0.3
    min_num_pts: 8

    # rotation grid criterion
    discretization_angle: 60

    # rotation threshold criterion
    max_angle_deg: 10

    # mask area criterion
    fit_mode: convex
    ratio_threshold: 0.6
    debug_viz: false
    debug_dir: /home/justin/code/point-to-pose/debug/criterion

optimizer:
  type: isam2
  params:
    relinearize_threshold: 0.1
    relinearize_skip: 1
    prior_noise_param: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

visualization:
  params:
    visualize_points: true
    # uncertainty, visible, visible_valid, visible_uncertainty, registration_used_valid, registration_correspondence, frame_id
    points_vis_method: visible_uncertainty
    save_images: True
    output_image_dir: /home/justin/code/point-to-pose/debug/output_images
